#!/usr/bin/env python3

import argparse
import json
import pathlib
import re
import sys
from typing import Any


HEADER_PROLOGUE = """// This file is generated by test/analysis/merge_client_hello_fixture_summary.py.
// Do not edit by hand. Refresh the frozen corpus first, review the diff,
// then regenerate this header from the checked-in JSON artifacts.

#pragma once

#include \"td/utils/common.h\"

namespace td {
namespace mtproto {
namespace test {
namespace fixtures {
namespace reviewed {

struct KeyShareExpectation final {
  uint16 group{0};
  uint16 key_exchange_length{0};
  bool is_grease_group{false};
};

struct EchExpectation final {
  bool present{false};
  uint8 outer_type{0};
  uint16 kdf_id{0};
  uint16 aead_id{0};
  uint16 enc_length{0};
  uint16 payload_length{0};
};

"""

HEADER_EPILOGUE = """
}  // namespace reviewed
}  // namespace fixtures
}  // namespace test
}  // namespace mtproto
}  // namespace td
"""


def load_json(path: pathlib.Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as infile:
        return json.load(infile)


def sanitize_identifier(name: str) -> str:
    return re.sub(r"[^0-9A-Za-z]+", "_", name).strip("_")


def hex_to_int(text: str) -> int:
    return int(text, 16)


def cpp_u16(value: str) -> str:
    return f"0x{hex_to_int(value):04X}"


def cpp_u8(value: str) -> str:
    return f"0x{int(value, 16):02X}"


def cpp_bool(value: bool) -> str:
    return "true" if value else "false"


def cpp_string_vector(name: str, values: list[str]) -> str:
    body = ", ".join(f'\"{value}\"' for value in values)
    return f"inline const vector<string> {name} = {{{body}}};"


def cpp_u16_vector(name: str, values: list[str]) -> str:
    body = ", ".join(cpp_u16(value) for value in values)
    return f"inline const vector<uint16> {name} = {{{body}}};"


def cpp_key_share_vector(name: str, entries: list[dict[str, Any]]) -> str:
    parts = []
    for entry in entries:
        parts.append(
            "{" + ", ".join(
                [
                    cpp_u16(entry["group"]),
                    str(entry["key_exchange_length"]),
                    cpp_bool(entry["is_grease_group"]),
                ]
            ) + "}"
        )
    return f"inline const vector<KeyShareExpectation> {name} = {{{', '.join(parts)}}};"


def cpp_ech_expectation(name: str, ech: dict[str, Any] | None) -> str:
    if not ech:
        return f"inline constexpr EchExpectation {name}{{false, 0, 0, 0, 0, 0}};"
    return (
        f"inline constexpr EchExpectation {name}{{true, {cpp_u8(ech['outer_type'])}, {cpp_u16(ech['kdf_id'])}, "
        f"{cpp_u16(ech['aead_id'])}, {ech['enc_length']}, {ech['payload_length']}}};"
    )


def emit_fixture_block(artifact: dict[str, Any], sample: dict[str, Any], prefix: str) -> list[str]:
    lines: list[str] = []
    lines.append(f"// fixture_id={sample['fixture_id']}")
    lines.append(f"inline constexpr const char {prefix}FixtureId[] = \"{sample['fixture_id']}\";")
    lines.append(f"inline constexpr const char {prefix}SourcePath[] = \"{artifact['source_path']}\";")
    lines.append(f"inline constexpr const char {prefix}SourceSha256[] = \"{artifact['source_sha256']}\";")
    lines.append(f"inline constexpr const char {prefix}CaptureDateUtc[] = \"{artifact['capture_date_utc']}\";")
    lines.append(f"inline constexpr const char {prefix}ParserVersion[] = \"{artifact['parser_version']}\";")
    lines.append(f"inline constexpr const char {prefix}ScenarioId[] = \"{artifact['scenario_id']}\";")
    lines.append(f"inline constexpr const char {prefix}RouteMode[] = \"{artifact['route_mode']}\";")
    lines.append(f"inline constexpr const char {prefix}Sni[] = \"{sample['sni']}\";")
    lines.append(f"inline constexpr uint32 {prefix}FrameNumber = {sample['frame_number']};")
    lines.append(f"inline constexpr uint32 {prefix}TcpStream = {sample['tcp_stream']};")
    lines.append(f"inline constexpr uint16 {prefix}RecordLength = {sample['record_length']};")
    lines.append(f"inline constexpr uint16 {prefix}HandshakeLength = {sample['handshake_length']};")
    lines.append(cpp_u16_vector(f"{prefix}CipherSuites", sample["cipher_suites"]))
    lines.append(cpp_u16_vector(f"{prefix}NonGreaseCipherSuites", sample["non_grease_cipher_suites"]))
    lines.append(cpp_u16_vector(f"{prefix}SupportedGroups", sample["supported_groups"]))
    lines.append(cpp_u16_vector(f"{prefix}NonGreaseSupportedGroups", sample["non_grease_supported_groups"]))
    lines.append(cpp_u16_vector(f"{prefix}ExtensionOrder", sample["extension_types"]))
    lines.append(cpp_u16_vector(f"{prefix}NonGreaseExtensionsWithoutPadding", sample["non_grease_extensions_without_padding"]))
    lines.append(cpp_string_vector(f"{prefix}AlpnProtocols", sample.get("alpn_protocols", [])))
    lines.append(cpp_u16_vector(f"{prefix}CompressCertificateAlgorithms", sample.get("compress_certificate_algorithms", [])))
    lines.append(cpp_key_share_vector(f"{prefix}KeyShareEntries", sample["key_share_entries"]))
    lines.append(cpp_ech_expectation(f"{prefix}Ech", sample.get("ech")))
    return lines


def choose_sample_key(stem: str, artifact: dict[str, Any], sample: dict[str, Any]) -> str:
    base = artifact.get("profile_id") or stem.replace(".clienthello", "")
    if len(artifact.get("samples", [])) > 1:
        base = f"{base}_frame{sample['frame_number']}"
    return sanitize_identifier(base)


def merge_artifacts(input_dir: pathlib.Path) -> str:
    artifact_paths = sorted(input_dir.glob("*.json"))
    if not artifact_paths:
        raise SystemExit(f"no JSON artifacts found in {input_dir}")

    lines: list[str] = [HEADER_PROLOGUE.rstrip(), ""]
    seen_prefixes: set[str] = set()

    for artifact_path in artifact_paths:
        artifact = load_json(artifact_path)
        samples = artifact.get("samples", [])
        if not samples:
            raise SystemExit(f"artifact has no samples: {artifact_path}")
        stem = artifact_path.stem
        lines.append(f"// merged_from={artifact_path}")
        for sample in samples:
            prefix = choose_sample_key(stem, artifact, sample)
            if prefix in seen_prefixes:
                raise SystemExit(f"duplicate generated fixture prefix: {prefix}")
            seen_prefixes.add(prefix)
            lines.extend(emit_fixture_block(artifact, sample, prefix))
            lines.append("")

    # Stable aliases for the current PR-2 browser-capture tests.
    aliases = {
        "ChromeBatch1Reference": "chrome144_batch1",
        "FirefoxBatch1Reference": "firefox148_batch1",
        "Chrome146_75Batch1Reference": "chrome146_75_batch1",
        "Chrome146_177Batch1Reference": "chrome146_177_batch1",
        "Tdesktop673Batch1Reference": "tdesktop673_batch1",
        "Firefox149Batch1Reference": "firefox149_batch1",
    }
    lines.append("// reviewed aliases used by PR-2 tests")
    for alias, target in aliases.items():
        target_prefix = sanitize_identifier(target)
        lines.append(f"inline const auto &k{alias}NonGreaseCipherSuites = {target_prefix}NonGreaseCipherSuites;")
        lines.append(f"inline const auto &k{alias}CipherSuites = {target_prefix}CipherSuites;")
        lines.append(f"inline const auto &k{alias}SupportedGroups = {target_prefix}SupportedGroups;")
        lines.append(f"inline const auto &k{alias}NonGreaseSupportedGroups = {target_prefix}NonGreaseSupportedGroups;")
        lines.append(f"inline const auto &k{alias}ExtensionOrder = {target_prefix}ExtensionOrder;")
        lines.append(f"inline const auto &k{alias}NonGreaseExtensionsWithoutPadding = {target_prefix}NonGreaseExtensionsWithoutPadding;")
        lines.append(f"inline const auto &k{alias}CompressCertificateAlgorithms = {target_prefix}CompressCertificateAlgorithms;")
        lines.append(f"inline const auto &k{alias}KeyShareEntries = {target_prefix}KeyShareEntries;")
        lines.append(f"inline constexpr auto k{alias}Ech = {target_prefix}Ech;")
    lines.append(HEADER_EPILOGUE.lstrip("\n"))
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Merge frozen ClientHello fixture artifacts into a single reviewed summary header for PR-2 tests."
    )
    parser.add_argument(
        "--input-dir",
        default="test/analysis/fixtures/clienthello/batch1",
        help="Directory containing frozen JSON artifacts",
    )
    parser.add_argument(
        "--out-header",
        default="test/stealth/ReviewedClientHelloFixtures.h",
        help="Generated C++ header path",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    input_dir = pathlib.Path(args.input_dir).resolve()
    output_path = pathlib.Path(args.out_header).resolve()
    merged = merge_artifacts(input_dir)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(merged, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())