# SPDX-FileCopyrightText: Copyright 2026 telemt community
# SPDX-License-Identifier: MIT
# telemt: https://github.com/telemt
# telemt: https://t.me/telemtrs

from __future__ import annotations

import argparse
import pathlib
import re
from typing import Iterable
from typing import Sequence


SQLITE_IDENTIFIER_RE = re.compile(r"(?<![A-Za-z0-9_])sqlite3[A-Za-z0-9_]*(?![A-Za-z0-9_]|\.)")
COMMENT_OR_LITERAL_RE = re.compile(
    r"//[^\n]*|/\*.*?\*/|\"(?:\\.|[^\"\\])*\"|'(?:\\.|[^'\\])*'",
    re.DOTALL,
)
PREPROCESSOR_CONDITIONAL_NAME_RE = re.compile(
    r"^\s*#\s*ifn?def\s+(sqlite3[A-Za-z0-9_]*)(?![A-Za-z0-9_]|\.)",
    re.MULTILINE,
)
PREPROCESSOR_DEFINE_NAME_RE = re.compile(
    r"^\s*#\s*(?:define|undef)\s+(sqlite3[A-Za-z0-9_]*)(?![A-Za-z0-9_]|\.)",
    re.MULTILINE,
)
PREPROCESSOR_IF_LINE_RE = re.compile(r"^\s*#\s*(?:if|elif)\b[^\n]*$", re.MULTILINE)
DEFINED_IDENTIFIER_RE = re.compile(
    r"\bdefined\s*(?:\(\s*(sqlite3[A-Za-z0-9_]*)(?![A-Za-z0-9_]|\.)\s*\)|\s+(sqlite3[A-Za-z0-9_]*)(?![A-Za-z0-9_]|\.))"
)


def _strip_comments_and_literals(text: str) -> str:
    def replace(match: re.Match[str]) -> str:
        return "".join("\n" if ch == "\n" else " " for ch in match.group(0))

    return COMMENT_OR_LITERAL_RE.sub(replace, text)


def _collect_conditional_guard_names(text: str) -> set[str]:
    macro_names = set(PREPROCESSOR_CONDITIONAL_NAME_RE.findall(text))
    for line in PREPROCESSOR_IF_LINE_RE.findall(text):
        for left, right in DEFINED_IDENTIFIER_RE.findall(line):
            if left:
                macro_names.add(left)
            if right:
                macro_names.add(right)
    return macro_names


def _collect_defined_macro_names(text: str) -> set[str]:
    return set(PREPROCESSOR_DEFINE_NAME_RE.findall(text))


def collect_sqlite_identifiers(texts: Iterable[str]) -> list[str]:
    identifiers: set[str] = set()
    for text in texts:
        current_identifiers = set(SQLITE_IDENTIFIER_RE.findall(_strip_comments_and_literals(text)))
        current_identifiers.difference_update(_collect_conditional_guard_names(text))
        identifiers.update(current_identifiers)
    return sorted(identifiers)


def collect_sqlite_identifiers_from_files(paths: Sequence[pathlib.Path]) -> list[str]:
    identifiers: set[str] = set()
    for path in paths:
        text = path.read_text(encoding="utf-8", errors="replace")
        current_identifiers = set(SQLITE_IDENTIFIER_RE.findall(_strip_comments_and_literals(text)))
        current_identifiers.difference_update(_collect_conditional_guard_names(text))
        if path.suffix == ".c":
            current_identifiers.difference_update(_collect_defined_macro_names(text))
        identifiers.update(current_identifiers)
    return sorted(identifiers)


def _normalize_source_path(path: pathlib.Path) -> str:
    if not path.is_absolute():
        return path.as_posix()

    try:
        sqlite_index = path.parts.index("sqlite")
    except ValueError:
        return path.as_posix()

    return pathlib.Path(*path.parts[sqlite_index:]).as_posix()


def render_rename_header(identifiers: Sequence[str], source_paths: Sequence[pathlib.Path]) -> str:
    unique_identifiers = sorted(set(identifiers))
    source_list = ", ".join(_normalize_source_path(path) for path in source_paths)
    lines = [
        "// SPDX-FileCopyrightText: Copyright 2026 telemt community",
        "// SPDX-License-Identifier: MIT",
        "// telemt: https://github.com/telemt",
        "// telemt: https://t.me/telemtrs",
        "// Auto-generated by tools/sqlite/generate_tdsqlite_rename.py.",
        f"// Source inputs: {source_list}",
        "",
        "#ifndef TDSQLITE_RENAME_H",
        "#define TDSQLITE_RENAME_H",
        "",
    ]
    for identifier in unique_identifiers:
        lines.append(f"#define {identifier} td{identifier}")
    lines.extend(["", "#endif  // TDSQLITE_RENAME_H", ""])
    return "\n".join(lines)


def _write_output(path: pathlib.Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the tdsqlite rename compatibility header.")
    parser.add_argument("--output", required=True, type=pathlib.Path, help="Path to the generated rename header.")
    parser.add_argument("inputs", nargs="+", type=pathlib.Path, help="Upstream SQLite files used to collect sqlite3* identifiers.")
    args = parser.parse_args(argv)

    content = render_rename_header(collect_sqlite_identifiers_from_files(args.inputs), args.inputs)
    _write_output(args.output, content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())