// This file is generated by test/analysis/merge_client_hello_fixture_summary.py.
// Do not edit by hand. Refresh the frozen corpus first, review the diff,
// then regenerate this header from the checked-in JSON artifacts.

#pragma once

#include "td/utils/common.h"

namespace td {
namespace mtproto {
namespace test {
namespace fixtures {
namespace reviewed {

struct KeyShareExpectation final {
  uint16 group{0};
  uint16 key_exchange_length{0};
  bool is_grease_group{false};
};

struct EchExpectation final {
  bool present{false};
  uint8 outer_type{0};
  uint16 kdf_id{0};
  uint16 aead_id{0};
  uint16 enc_length{0};
  uint16 payload_length{0};
};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/batch1/chrome144_batch1.clienthello.json
// fixture_id=chrome144_batch1:frame5
inline constexpr const char chrome144_batch1FixtureId[] = "chrome144_batch1:frame5";
inline constexpr const char chrome144_batch1SourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/batch 1/clienthello-chrome144.0.7559.109-ubuntu24.04.pcapng";
inline constexpr const char chrome144_batch1SourceSha256[] = "0b1f5304574735f6e3e87406d1f75f41d2b1823c898391c98da10d89a8008177";
inline constexpr const char chrome144_batch1CaptureDateUtc[] = "2026-04-07T10:15:21Z";
inline constexpr const char chrome144_batch1ParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char chrome144_batch1ScenarioId[] = "batch1_ubuntu24_clienthello";
inline constexpr const char chrome144_batch1RouteMode[] = "non_ru";
inline constexpr const char chrome144_batch1Sni[] = "viiita.fun";
inline constexpr uint32 chrome144_batch1FrameNumber = 5;
inline constexpr uint32 chrome144_batch1TcpStream = 0;
inline constexpr uint16 chrome144_batch1RecordLength = 1779;
inline constexpr uint16 chrome144_batch1HandshakeLength = 1775;
inline const vector<uint16> chrome144_batch1CipherSuites = {0xCACA, 0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome144_batch1NonGreaseCipherSuites = {0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome144_batch1SupportedGroups = {0xDADA, 0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome144_batch1NonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome144_batch1ExtensionOrder = {0xCACA, 0x000A, 0x0000, 0x002D, 0x0023, 0x000B, 0x002B, 0x0033, 0xFF01, 0xFE0D, 0x0010, 0x000D, 0x0017, 0x44CD, 0x001B, 0x0005, 0x0012, 0x2A2A};
inline const vector<uint16> chrome144_batch1NonGreaseExtensionsWithoutPadding = {0x000A, 0x0000, 0x002D, 0x0023, 0x000B, 0x002B, 0x0033, 0xFF01, 0xFE0D, 0x0010, 0x000D, 0x0017, 0x44CD, 0x001B, 0x0005, 0x0012};
inline const vector<string> chrome144_batch1AlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> chrome144_batch1CompressCertificateAlgorithms = {0x0002};
inline const vector<KeyShareExpectation> chrome144_batch1KeyShareEntries = {{0xDADA, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation chrome144_batch1Ech{true, 0x00, 0x0001, 0x0001, 32, 208};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/batch1/chrome146_177_batch1.clienthello.json
// fixture_id=chrome146_177_batch1:frame5
inline constexpr const char chrome146_177_batch1FixtureId[] = "chrome146_177_batch1:frame5";
inline constexpr const char chrome146_177_batch1SourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/batch 1/chrome146.0.7680.177-1.pcapng";
inline constexpr const char chrome146_177_batch1SourceSha256[] = "fca18c4290183273b647915300bd1e2ed353e29ff3acb0361c93153e03d95735";
inline constexpr const char chrome146_177_batch1CaptureDateUtc[] = "2026-04-07T03:01:09Z";
inline constexpr const char chrome146_177_batch1ParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char chrome146_177_batch1ScenarioId[] = "batch1_ubuntu24_clienthello";
inline constexpr const char chrome146_177_batch1RouteMode[] = "non_ru";
inline constexpr const char chrome146_177_batch1Sni[] = "viiita.fun";
inline constexpr uint32 chrome146_177_batch1FrameNumber = 5;
inline constexpr uint32 chrome146_177_batch1TcpStream = 0;
inline constexpr uint16 chrome146_177_batch1RecordLength = 1794;
inline constexpr uint16 chrome146_177_batch1HandshakeLength = 1790;
inline const vector<uint16> chrome146_177_batch1CipherSuites = {0xEAEA, 0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome146_177_batch1NonGreaseCipherSuites = {0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome146_177_batch1SupportedGroups = {0x8A8A, 0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome146_177_batch1NonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome146_177_batch1ExtensionOrder = {0x6A6A, 0x001B, 0x000A, 0xFE0D, 0x000B, 0x0023, 0x0010, 0x0017, 0xFF01, 0x0005, 0x0033, 0x002B, 0x000D, 0x0012, 0x002D, 0x0000, 0x44CD, 0x4A4A, 0x0029};
inline const vector<uint16> chrome146_177_batch1NonGreaseExtensionsWithoutPadding = {0x001B, 0x000A, 0xFE0D, 0x000B, 0x0023, 0x0010, 0x0017, 0xFF01, 0x0005, 0x0033, 0x002B, 0x000D, 0x0012, 0x002D, 0x0000, 0x44CD, 0x0029};
inline const vector<string> chrome146_177_batch1AlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> chrome146_177_batch1CompressCertificateAlgorithms = {0x0002};
inline const vector<KeyShareExpectation> chrome146_177_batch1KeyShareEntries = {{0x8A8A, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation chrome146_177_batch1Ech{true, 0x00, 0x0001, 0x0001, 32, 144};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/batch1/chrome146_75_batch1.clienthello.json
// fixture_id=chrome146_75_batch1:frame5
inline constexpr const char chrome146_75_batch1FixtureId[] = "chrome146_75_batch1:frame5";
inline constexpr const char chrome146_75_batch1SourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/batch 1/chrome146.0.7680.75-1.pcapng";
inline constexpr const char chrome146_75_batch1SourceSha256[] = "cfab11484e648613605053a3b4cffb0d36fb22379c8ef60f198fb6d2a2e5787b";
inline constexpr const char chrome146_75_batch1CaptureDateUtc[] = "2026-04-07T02:56:06Z";
inline constexpr const char chrome146_75_batch1ParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char chrome146_75_batch1ScenarioId[] = "batch1_ubuntu24_clienthello";
inline constexpr const char chrome146_75_batch1RouteMode[] = "non_ru";
inline constexpr const char chrome146_75_batch1Sni[] = "viiita.fun";
inline constexpr uint32 chrome146_75_batch1FrameNumber = 5;
inline constexpr uint32 chrome146_75_batch1TcpStream = 0;
inline constexpr uint16 chrome146_75_batch1RecordLength = 1715;
inline constexpr uint16 chrome146_75_batch1HandshakeLength = 1711;
inline const vector<uint16> chrome146_75_batch1CipherSuites = {0xDADA, 0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome146_75_batch1NonGreaseCipherSuites = {0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome146_75_batch1SupportedGroups = {0x7A7A, 0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome146_75_batch1NonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome146_75_batch1ExtensionOrder = {0xEAEA, 0xFF01, 0x0010, 0x0033, 0xFE0D, 0x0012, 0x000A, 0x0000, 0x0023, 0x0017, 0x001B, 0x000D, 0x002B, 0x000B, 0x0005, 0x002D, 0x44CD, 0x1A1A};
inline const vector<uint16> chrome146_75_batch1NonGreaseExtensionsWithoutPadding = {0xFF01, 0x0010, 0x0033, 0xFE0D, 0x0012, 0x000A, 0x0000, 0x0023, 0x0017, 0x001B, 0x000D, 0x002B, 0x000B, 0x0005, 0x002D, 0x44CD};
inline const vector<string> chrome146_75_batch1AlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> chrome146_75_batch1CompressCertificateAlgorithms = {0x0002};
inline const vector<KeyShareExpectation> chrome146_75_batch1KeyShareEntries = {{0x7A7A, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation chrome146_75_batch1Ech{true, 0x00, 0x0001, 0x0001, 32, 144};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/batch1/firefox148_batch1.clienthello.json
// fixture_id=firefox148_batch1:frame5
inline constexpr const char firefox148_batch1FixtureId[] = "firefox148_batch1:frame5";
inline constexpr const char firefox148_batch1SourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/batch 1/clienthello-firefox148.0.2-ubuntu24.04.pcapng";
inline constexpr const char firefox148_batch1SourceSha256[] = "c93bf5b06b764ad2f8162b79dfc5f96252c54f2b0de1d04f3fe37cb40b10c400";
inline constexpr const char firefox148_batch1CaptureDateUtc[] = "2026-04-07T10:36:16Z";
inline constexpr const char firefox148_batch1ParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char firefox148_batch1ScenarioId[] = "batch1_ubuntu24_clienthello";
inline constexpr const char firefox148_batch1RouteMode[] = "non_ru";
inline constexpr const char firefox148_batch1Sni[] = "viiita.fun";
inline constexpr uint32 firefox148_batch1FrameNumber = 5;
inline constexpr uint32 firefox148_batch1TcpStream = 0;
inline constexpr uint16 firefox148_batch1RecordLength = 1890;
inline constexpr uint16 firefox148_batch1HandshakeLength = 1886;
inline const vector<uint16> firefox148_batch1CipherSuites = {0x1301, 0x1303, 0x1302, 0xC02B, 0xC02F, 0xCCA9, 0xCCA8, 0xC02C, 0xC030, 0xC00A, 0xC009, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> firefox148_batch1NonGreaseCipherSuites = {0x1301, 0x1303, 0x1302, 0xC02B, 0xC02F, 0xCCA9, 0xCCA8, 0xC02C, 0xC030, 0xC00A, 0xC009, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> firefox148_batch1SupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019, 0x0100, 0x0101};
inline const vector<uint16> firefox148_batch1NonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019, 0x0100, 0x0101};
inline const vector<uint16> firefox148_batch1ExtensionOrder = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0023, 0x0010, 0x0005, 0x0022, 0x0012, 0x0033, 0x002B, 0x000D, 0x002D, 0x001C, 0x001B, 0xFE0D};
inline const vector<uint16> firefox148_batch1NonGreaseExtensionsWithoutPadding = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0023, 0x0010, 0x0005, 0x0022, 0x0012, 0x0033, 0x002B, 0x000D, 0x002D, 0x001C, 0x001B, 0xFE0D};
inline const vector<string> firefox148_batch1AlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> firefox148_batch1CompressCertificateAlgorithms = {0x0001, 0x0002, 0x0003};
inline const vector<KeyShareExpectation> firefox148_batch1KeyShareEntries = {{0x11EC, 1216, false}, {0x001D, 32, false}, {0x0017, 65, false}};
inline constexpr EchExpectation firefox148_batch1Ech{true, 0x00, 0x0001, 0x0003, 32, 239};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/batch1/firefox149_batch1.clienthello.json
// fixture_id=firefox149_batch1:frame5
inline constexpr const char firefox149_batch1FixtureId[] = "firefox149_batch1:frame5";
inline constexpr const char firefox149_batch1SourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/batch 1/firefox149.0.pcapng";
inline constexpr const char firefox149_batch1SourceSha256[] = "f7e0c07cc15b25654cab26a29cafcc16fbdcec4304cacbe0ffc831fca93a2fea";
inline constexpr const char firefox149_batch1CaptureDateUtc[] = "2026-04-07T03:50:15Z";
inline constexpr const char firefox149_batch1ParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char firefox149_batch1ScenarioId[] = "batch1_ubuntu24_clienthello";
inline constexpr const char firefox149_batch1RouteMode[] = "non_ru";
inline constexpr const char firefox149_batch1Sni[] = "viiita.fun";
inline constexpr uint32 firefox149_batch1FrameNumber = 5;
inline constexpr uint32 firefox149_batch1TcpStream = 0;
inline constexpr uint16 firefox149_batch1RecordLength = 1890;
inline constexpr uint16 firefox149_batch1HandshakeLength = 1886;
inline const vector<uint16> firefox149_batch1CipherSuites = {0x1301, 0x1303, 0x1302, 0xC02B, 0xC02F, 0xCCA9, 0xCCA8, 0xC02C, 0xC030, 0xC00A, 0xC009, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> firefox149_batch1NonGreaseCipherSuites = {0x1301, 0x1303, 0x1302, 0xC02B, 0xC02F, 0xCCA9, 0xCCA8, 0xC02C, 0xC030, 0xC00A, 0xC009, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> firefox149_batch1SupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019, 0x0100, 0x0101};
inline const vector<uint16> firefox149_batch1NonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019, 0x0100, 0x0101};
inline const vector<uint16> firefox149_batch1ExtensionOrder = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0023, 0x0010, 0x0005, 0x0022, 0x0012, 0x0033, 0x002B, 0x000D, 0x002D, 0x001C, 0x001B, 0xFE0D};
inline const vector<uint16> firefox149_batch1NonGreaseExtensionsWithoutPadding = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0023, 0x0010, 0x0005, 0x0022, 0x0012, 0x0033, 0x002B, 0x000D, 0x002D, 0x001C, 0x001B, 0xFE0D};
inline const vector<string> firefox149_batch1AlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> firefox149_batch1CompressCertificateAlgorithms = {0x0001, 0x0002, 0x0003};
inline const vector<KeyShareExpectation> firefox149_batch1KeyShareEntries = {{0x11EC, 1216, false}, {0x001D, 32, false}, {0x0017, 65, false}};
inline constexpr EchExpectation firefox149_batch1Ech{true, 0x00, 0x0001, 0x0001, 32, 239};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/batch1/tdesktop673_batch1.clienthello.json
// fixture_id=tdesktop673_batch1:frame5
inline constexpr const char tdesktop673_batch1FixtureId[] = "tdesktop673_batch1:frame5";
inline constexpr const char tdesktop673_batch1SourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/batch 1/clienthello-tdesktop6.7.3-ubuntu24.04.pcapng";
inline constexpr const char tdesktop673_batch1SourceSha256[] = "7713ff5b35fe02cbcc16350019da0fd21d68011c7fe1ccece801ae7323f72487";
inline constexpr const char tdesktop673_batch1CaptureDateUtc[] = "2026-04-07T10:02:20Z";
inline constexpr const char tdesktop673_batch1ParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char tdesktop673_batch1ScenarioId[] = "batch1_ubuntu24_clienthello";
inline constexpr const char tdesktop673_batch1RouteMode[] = "non_ru";
inline constexpr const char tdesktop673_batch1Sni[] = "viiita.fun";
inline constexpr uint32 tdesktop673_batch1FrameNumber = 5;
inline constexpr uint32 tdesktop673_batch1TcpStream = 0;
inline constexpr uint16 tdesktop673_batch1RecordLength = 1779;
inline constexpr uint16 tdesktop673_batch1HandshakeLength = 1775;
inline const vector<uint16> tdesktop673_batch1CipherSuites = {0xDADA, 0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> tdesktop673_batch1NonGreaseCipherSuites = {0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> tdesktop673_batch1SupportedGroups = {0x1A1A, 0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> tdesktop673_batch1NonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> tdesktop673_batch1ExtensionOrder = {0x6A6A, 0x002D, 0xFE0D, 0x002B, 0x0012, 0x44CD, 0x000A, 0x0023, 0x000B, 0x0005, 0x0000, 0x0010, 0x0033, 0x0017, 0xFF01, 0x000D, 0x001B, 0x4A4A};
inline const vector<uint16> tdesktop673_batch1NonGreaseExtensionsWithoutPadding = {0x002D, 0xFE0D, 0x002B, 0x0012, 0x44CD, 0x000A, 0x0023, 0x000B, 0x0005, 0x0000, 0x0010, 0x0033, 0x0017, 0xFF01, 0x000D, 0x001B};
inline const vector<string> tdesktop673_batch1AlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> tdesktop673_batch1CompressCertificateAlgorithms = {0x0002};
inline const vector<KeyShareExpectation> tdesktop673_batch1KeyShareEntries = {{0x1A1A, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation tdesktop673_batch1Ech{true, 0x00, 0x0001, 0x0001, 32, 208};

// reviewed aliases used by PR-2 tests
inline const auto &kChromeBatch1ReferenceNonGreaseCipherSuites = chrome144_batch1NonGreaseCipherSuites;
inline const auto &kChromeBatch1ReferenceCipherSuites = chrome144_batch1CipherSuites;
inline const auto &kChromeBatch1ReferenceSupportedGroups = chrome144_batch1SupportedGroups;
inline const auto &kChromeBatch1ReferenceNonGreaseSupportedGroups = chrome144_batch1NonGreaseSupportedGroups;
inline const auto &kChromeBatch1ReferenceExtensionOrder = chrome144_batch1ExtensionOrder;
inline const auto &kChromeBatch1ReferenceNonGreaseExtensionsWithoutPadding = chrome144_batch1NonGreaseExtensionsWithoutPadding;
inline const auto &kChromeBatch1ReferenceCompressCertificateAlgorithms = chrome144_batch1CompressCertificateAlgorithms;
inline const auto &kChromeBatch1ReferenceKeyShareEntries = chrome144_batch1KeyShareEntries;
inline constexpr auto kChromeBatch1ReferenceEch = chrome144_batch1Ech;
inline const auto &kFirefoxBatch1ReferenceNonGreaseCipherSuites = firefox148_batch1NonGreaseCipherSuites;
inline const auto &kFirefoxBatch1ReferenceCipherSuites = firefox148_batch1CipherSuites;
inline const auto &kFirefoxBatch1ReferenceSupportedGroups = firefox148_batch1SupportedGroups;
inline const auto &kFirefoxBatch1ReferenceNonGreaseSupportedGroups = firefox148_batch1NonGreaseSupportedGroups;
inline const auto &kFirefoxBatch1ReferenceExtensionOrder = firefox148_batch1ExtensionOrder;
inline const auto &kFirefoxBatch1ReferenceNonGreaseExtensionsWithoutPadding = firefox148_batch1NonGreaseExtensionsWithoutPadding;
inline const auto &kFirefoxBatch1ReferenceCompressCertificateAlgorithms = firefox148_batch1CompressCertificateAlgorithms;
inline const auto &kFirefoxBatch1ReferenceKeyShareEntries = firefox148_batch1KeyShareEntries;
inline constexpr auto kFirefoxBatch1ReferenceEch = firefox148_batch1Ech;
inline const auto &kChrome146_75Batch1ReferenceNonGreaseCipherSuites = chrome146_75_batch1NonGreaseCipherSuites;
inline const auto &kChrome146_75Batch1ReferenceCipherSuites = chrome146_75_batch1CipherSuites;
inline const auto &kChrome146_75Batch1ReferenceSupportedGroups = chrome146_75_batch1SupportedGroups;
inline const auto &kChrome146_75Batch1ReferenceNonGreaseSupportedGroups = chrome146_75_batch1NonGreaseSupportedGroups;
inline const auto &kChrome146_75Batch1ReferenceExtensionOrder = chrome146_75_batch1ExtensionOrder;
inline const auto &kChrome146_75Batch1ReferenceNonGreaseExtensionsWithoutPadding = chrome146_75_batch1NonGreaseExtensionsWithoutPadding;
inline const auto &kChrome146_75Batch1ReferenceCompressCertificateAlgorithms = chrome146_75_batch1CompressCertificateAlgorithms;
inline const auto &kChrome146_75Batch1ReferenceKeyShareEntries = chrome146_75_batch1KeyShareEntries;
inline constexpr auto kChrome146_75Batch1ReferenceEch = chrome146_75_batch1Ech;
inline const auto &kChrome146_177Batch1ReferenceNonGreaseCipherSuites = chrome146_177_batch1NonGreaseCipherSuites;
inline const auto &kChrome146_177Batch1ReferenceCipherSuites = chrome146_177_batch1CipherSuites;
inline const auto &kChrome146_177Batch1ReferenceSupportedGroups = chrome146_177_batch1SupportedGroups;
inline const auto &kChrome146_177Batch1ReferenceNonGreaseSupportedGroups = chrome146_177_batch1NonGreaseSupportedGroups;
inline const auto &kChrome146_177Batch1ReferenceExtensionOrder = chrome146_177_batch1ExtensionOrder;
inline const auto &kChrome146_177Batch1ReferenceNonGreaseExtensionsWithoutPadding = chrome146_177_batch1NonGreaseExtensionsWithoutPadding;
inline const auto &kChrome146_177Batch1ReferenceCompressCertificateAlgorithms = chrome146_177_batch1CompressCertificateAlgorithms;
inline const auto &kChrome146_177Batch1ReferenceKeyShareEntries = chrome146_177_batch1KeyShareEntries;
inline constexpr auto kChrome146_177Batch1ReferenceEch = chrome146_177_batch1Ech;
inline const auto &kTdesktop673Batch1ReferenceNonGreaseCipherSuites = tdesktop673_batch1NonGreaseCipherSuites;
inline const auto &kTdesktop673Batch1ReferenceCipherSuites = tdesktop673_batch1CipherSuites;
inline const auto &kTdesktop673Batch1ReferenceSupportedGroups = tdesktop673_batch1SupportedGroups;
inline const auto &kTdesktop673Batch1ReferenceNonGreaseSupportedGroups = tdesktop673_batch1NonGreaseSupportedGroups;
inline const auto &kTdesktop673Batch1ReferenceExtensionOrder = tdesktop673_batch1ExtensionOrder;
inline const auto &kTdesktop673Batch1ReferenceNonGreaseExtensionsWithoutPadding = tdesktop673_batch1NonGreaseExtensionsWithoutPadding;
inline const auto &kTdesktop673Batch1ReferenceCompressCertificateAlgorithms = tdesktop673_batch1CompressCertificateAlgorithms;
inline const auto &kTdesktop673Batch1ReferenceKeyShareEntries = tdesktop673_batch1KeyShareEntries;
inline constexpr auto kTdesktop673Batch1ReferenceEch = tdesktop673_batch1Ech;
inline const auto &kFirefox149Batch1ReferenceNonGreaseCipherSuites = firefox149_batch1NonGreaseCipherSuites;
inline const auto &kFirefox149Batch1ReferenceCipherSuites = firefox149_batch1CipherSuites;
inline const auto &kFirefox149Batch1ReferenceSupportedGroups = firefox149_batch1SupportedGroups;
inline const auto &kFirefox149Batch1ReferenceNonGreaseSupportedGroups = firefox149_batch1NonGreaseSupportedGroups;
inline const auto &kFirefox149Batch1ReferenceExtensionOrder = firefox149_batch1ExtensionOrder;
inline const auto &kFirefox149Batch1ReferenceNonGreaseExtensionsWithoutPadding = firefox149_batch1NonGreaseExtensionsWithoutPadding;
inline const auto &kFirefox149Batch1ReferenceCompressCertificateAlgorithms = firefox149_batch1CompressCertificateAlgorithms;
inline const auto &kFirefox149Batch1ReferenceKeyShareEntries = firefox149_batch1KeyShareEntries;
inline constexpr auto kFirefox149Batch1ReferenceEch = firefox149_batch1Ech;
}  // namespace reviewed
}  // namespace fixtures
}  // namespace test
}  // namespace mtproto
}  // namespace td
