// SPDX-FileCopyrightText: Copyright 2026 telemt community
// SPDX-License-Identifier: MIT
// telemt: https://github.com/telemt
// telemt: https://t.me/telemtrs
//

// This file is generated by test/analysis/merge_client_hello_fixture_summary.py.
// Do not edit by hand. Refresh the frozen corpus first, review the diff,
// then regenerate this header from the checked-in JSON artifacts.

#pragma once

#include "td/utils/common.h"

namespace td {
namespace mtproto {
namespace test {
namespace fixtures {
namespace reviewed {

struct KeyShareExpectation final {
    uint16 group{0};
    uint16 key_exchange_length{0};
    bool is_grease_group{false};
};

struct EchExpectation final {
    bool present{false};
    uint8 outer_type{0};
    uint16 kdf_id{0};
    uint16 aead_id{0};
    uint16 enc_length{0};
    uint16 payload_length{0};
};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/android/brave188_138_android13.clienthello.json
// fixture_id=brave188_138_android13:frame100
inline constexpr const char brave188_138_android13FixtureId[] = "brave188_138_android13:frame100";
inline constexpr const char brave188_138_android13SourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/Android/brave 1.88.138, android 13.pcap";
inline constexpr const char brave188_138_android13SourceSha256[] = "e7535149ea8f72cac723a3969505f067f6c7aa6cdd85ae6a275d336f17d2bf4c";
inline constexpr const char brave188_138_android13CaptureDateUtc[] = "2026-04-07T13:06:51Z";
inline constexpr const char brave188_138_android13ParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char brave188_138_android13ScenarioId[] = "android13_brave188_138_clienthello";
inline constexpr const char brave188_138_android13RouteMode[] = "non_ru_egress";
inline constexpr const char brave188_138_android13Sni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 brave188_138_android13FrameNumber = 100;
inline constexpr uint32 brave188_138_android13TcpStream = 1;
inline constexpr uint16 brave188_138_android13RecordLength = 1946;
inline constexpr uint16 brave188_138_android13HandshakeLength = 1942;
inline const vector<uint16> brave188_138_android13CipherSuites = {0x9A9A, 0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> brave188_138_android13NonGreaseCipherSuites = {0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> brave188_138_android13SupportedGroups = {0xAAAA, 0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> brave188_138_android13NonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> brave188_138_android13ExtensionOrder = {0xBABA, 0xFF01, 0x0012, 0xFE0D, 0x0033, 0x000D, 0x0023, 0x0005, 0x001B, 0x0000, 0x002B, 0x0010, 0x000A, 0x44CD, 0x0017, 0x002D, 0x000B, 0x2A2A, 0x0029};
inline const vector<uint16> brave188_138_android13NonGreaseExtensionsWithoutPadding = {0xFF01, 0x0012, 0xFE0D, 0x0033, 0x000D, 0x0023, 0x0005, 0x001B, 0x0000, 0x002B, 0x0010, 0x000A, 0x44CD, 0x0017, 0x002D, 0x000B, 0x0029};
inline const vector<string> brave188_138_android13AlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> brave188_138_android13CompressCertificateAlgorithms = {0x0002};
inline const vector<KeyShareExpectation> brave188_138_android13KeyShareEntries = {{0xAAAA, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation brave188_138_android13Ech{true, 0x00, 0x0001, 0x0001, 32, 208};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/android/chrome146_177_android16.clienthello.json
// fixture_id=chrome146_177_android16:frame94
inline constexpr const char chrome146_177_android16FixtureId[] = "chrome146_177_android16:frame94";
inline constexpr const char chrome146_177_android16SourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/Android/Android 16, Chrome 146.0.7680.177.pcap";
inline constexpr const char chrome146_177_android16SourceSha256[] = "dcabbd5e1ee2c97f2e46c583c9e959746abdcc1a6b0785fa42a2a1db5bd896b0";
inline constexpr const char chrome146_177_android16CaptureDateUtc[] = "2026-04-07T14:01:50Z";
inline constexpr const char chrome146_177_android16ParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char chrome146_177_android16ScenarioId[] = "android16_chrome146_177_clienthello";
inline constexpr const char chrome146_177_android16RouteMode[] = "non_ru_egress";
inline constexpr const char chrome146_177_android16Sni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 chrome146_177_android16FrameNumber = 94;
inline constexpr uint32 chrome146_177_android16TcpStream = 1;
inline constexpr uint16 chrome146_177_android16RecordLength = 1782;
inline constexpr uint16 chrome146_177_android16HandshakeLength = 1778;
inline const vector<uint16> chrome146_177_android16CipherSuites = {0x4A4A, 0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome146_177_android16NonGreaseCipherSuites = {0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome146_177_android16SupportedGroups = {0x4A4A, 0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome146_177_android16NonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome146_177_android16ExtensionOrder = {0xBABA, 0x0023, 0x0012, 0x0010, 0xFE0D, 0x0017, 0x000D, 0x002B, 0xFF01, 0x000B, 0x0033, 0x0005, 0x002D, 0x0000, 0x000A, 0x001B, 0xFAFA};
inline const vector<uint16> chrome146_177_android16NonGreaseExtensionsWithoutPadding = {0x0023, 0x0012, 0x0010, 0xFE0D, 0x0017, 0x000D, 0x002B, 0xFF01, 0x000B, 0x0033, 0x0005, 0x002D, 0x0000, 0x000A, 0x001B};
inline const vector<string> chrome146_177_android16AlpnProtocols = {"http/1.1"};
inline const vector<uint16> chrome146_177_android16CompressCertificateAlgorithms = {0x0002};
inline const vector<KeyShareExpectation> chrome146_177_android16KeyShareEntries = {{0x4A4A, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation chrome146_177_android16Ech{true, 0x00, 0x0001, 0x0001, 32, 208};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/android/chrome146_177_android16_pixel9proxl.clienthello.json
// fixture_id=chrome146_177_android16_pixel9proxl:frame129
inline constexpr const char chrome146_177_android16_pixel9proxlFixtureId[] = "chrome146_177_android16_pixel9proxl:frame129";
inline constexpr const char chrome146_177_android16_pixel9proxlSourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/Android/Chrome_146_0_7680_177_Android_16;_Pixel_9_Pro_XL_Build_CP1A_2603.pcap";
inline constexpr const char chrome146_177_android16_pixel9proxlSourceSha256[] = "ea0a09b56edeba1eb2b94b0df133d346d452cc6b67fe97f8c08ce55c459142ad";
inline constexpr const char chrome146_177_android16_pixel9proxlCaptureDateUtc[] = "2026-04-07T13:07:21Z";
inline constexpr const char chrome146_177_android16_pixel9proxlParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char chrome146_177_android16_pixel9proxlScenarioId[] = "android16_pixel9proxl_chrome146_177_clienthello";
inline constexpr const char chrome146_177_android16_pixel9proxlRouteMode[] = "non_ru_egress";
inline constexpr const char chrome146_177_android16_pixel9proxlSni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 chrome146_177_android16_pixel9proxlFrameNumber = 129;
inline constexpr uint32 chrome146_177_android16_pixel9proxlTcpStream = 1;
inline constexpr uint16 chrome146_177_android16_pixel9proxlRecordLength = 1750;
inline constexpr uint16 chrome146_177_android16_pixel9proxlHandshakeLength = 1746;
inline const vector<uint16> chrome146_177_android16_pixel9proxlCipherSuites = {0xFAFA, 0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome146_177_android16_pixel9proxlNonGreaseCipherSuites = {0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome146_177_android16_pixel9proxlSupportedGroups = {0x7A7A, 0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome146_177_android16_pixel9proxlNonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome146_177_android16_pixel9proxlExtensionOrder = {0x8A8A, 0x002D, 0x002B, 0x000A, 0x0005, 0xFE0D, 0x0023, 0x0012, 0x0010, 0x0033, 0x000D, 0x0000, 0x0017, 0x000B, 0x001B, 0xFF01, 0xDADA};
inline const vector<uint16> chrome146_177_android16_pixel9proxlNonGreaseExtensionsWithoutPadding = {0x002D, 0x002B, 0x000A, 0x0005, 0xFE0D, 0x0023, 0x0012, 0x0010, 0x0033, 0x000D, 0x0000, 0x0017, 0x000B, 0x001B, 0xFF01};
inline const vector<string> chrome146_177_android16_pixel9proxlAlpnProtocols = {"http/1.1"};
inline const vector<uint16> chrome146_177_android16_pixel9proxlCompressCertificateAlgorithms = {0x0002};
inline const vector<KeyShareExpectation> chrome146_177_android16_pixel9proxlKeyShareEntries = {{0x7A7A, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation chrome146_177_android16_pixel9proxlEch{true, 0x00, 0x0001, 0x0001, 32, 176};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/android/chrome146_177_oxygenos16_oneplus13.clienthello.json
// fixture_id=chrome146_177_oxygenos16_oneplus13:frame102
inline constexpr const char chrome146_177_oxygenos16_oneplus13FixtureId[] = "chrome146_177_oxygenos16_oneplus13:frame102";
inline constexpr const char chrome146_177_oxygenos16_oneplus13SourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/Android/Chrome 146.0.7680.177,OxygenOS 16,OnePlus 13.pcap";
inline constexpr const char chrome146_177_oxygenos16_oneplus13SourceSha256[] = "3be95fe6145904106908714f362de04bc497e9fa533d5bdf046c88f8e436d659";
inline constexpr const char chrome146_177_oxygenos16_oneplus13CaptureDateUtc[] = "2026-04-07T13:01:43Z";
inline constexpr const char chrome146_177_oxygenos16_oneplus13ParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char chrome146_177_oxygenos16_oneplus13ScenarioId[] = "android_oxygenos16_oneplus13_chrome146_177_clienthello";
inline constexpr const char chrome146_177_oxygenos16_oneplus13RouteMode[] = "non_ru_egress";
inline constexpr const char chrome146_177_oxygenos16_oneplus13Sni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 chrome146_177_oxygenos16_oneplus13FrameNumber = 102;
inline constexpr uint32 chrome146_177_oxygenos16_oneplus13TcpStream = 1;
inline constexpr uint16 chrome146_177_oxygenos16_oneplus13RecordLength = 1750;
inline constexpr uint16 chrome146_177_oxygenos16_oneplus13HandshakeLength = 1746;
inline const vector<uint16> chrome146_177_oxygenos16_oneplus13CipherSuites = {0x0A0A, 0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome146_177_oxygenos16_oneplus13NonGreaseCipherSuites = {0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome146_177_oxygenos16_oneplus13SupportedGroups = {0xFAFA, 0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome146_177_oxygenos16_oneplus13NonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome146_177_oxygenos16_oneplus13ExtensionOrder = {0x2A2A, 0x0017, 0x000A, 0xFF01, 0x000B, 0x002D, 0x0010, 0x000D, 0x002B, 0x0000, 0xFE0D, 0x0023, 0x0033, 0x001B, 0x0005, 0x0012, 0x7A7A};
inline const vector<uint16> chrome146_177_oxygenos16_oneplus13NonGreaseExtensionsWithoutPadding = {0x0017, 0x000A, 0xFF01, 0x000B, 0x002D, 0x0010, 0x000D, 0x002B, 0x0000, 0xFE0D, 0x0023, 0x0033, 0x001B, 0x0005, 0x0012};
inline const vector<string> chrome146_177_oxygenos16_oneplus13AlpnProtocols = {"http/1.1"};
inline const vector<uint16> chrome146_177_oxygenos16_oneplus13CompressCertificateAlgorithms = {0x0002};
inline const vector<KeyShareExpectation> chrome146_177_oxygenos16_oneplus13KeyShareEntries = {{0xFAFA, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation chrome146_177_oxygenos16_oneplus13Ech{true, 0x00, 0x0001, 0x0001, 32, 176};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/android/samsung_internet29_android16_galaxy_s25plus.clienthello.json
// fixture_id=samsung_internet29_android16_galaxy_s25plus:frame133
inline constexpr const char samsung_internet29_android16_galaxy_s25plusFixtureId[] = "samsung_internet29_android16_galaxy_s25plus:frame133";
inline constexpr const char samsung_internet29_android16_galaxy_s25plusSourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/Android/Samsung Galaxy S25+, Android 16, Samsung Internet Browser 29.0.pcap";
inline constexpr const char samsung_internet29_android16_galaxy_s25plusSourceSha256[] = "ffe2edd54f38a29fb69f3ecf9a781a991e4d7677af3ac9a4f622b66390722779";
inline constexpr const char samsung_internet29_android16_galaxy_s25plusCaptureDateUtc[] = "2026-04-07T13:05:40Z";
inline constexpr const char samsung_internet29_android16_galaxy_s25plusParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char samsung_internet29_android16_galaxy_s25plusScenarioId[] = "android16_galaxy_s25plus_samsung_internet29_clienthello";
inline constexpr const char samsung_internet29_android16_galaxy_s25plusRouteMode[] = "non_ru_egress";
inline constexpr const char samsung_internet29_android16_galaxy_s25plusSni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 samsung_internet29_android16_galaxy_s25plusFrameNumber = 133;
inline constexpr uint32 samsung_internet29_android16_galaxy_s25plusTcpStream = 1;
inline constexpr uint16 samsung_internet29_android16_galaxy_s25plusRecordLength = 1782;
inline constexpr uint16 samsung_internet29_android16_galaxy_s25plusHandshakeLength = 1778;
inline const vector<uint16> samsung_internet29_android16_galaxy_s25plusCipherSuites = {0xCACA, 0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> samsung_internet29_android16_galaxy_s25plusNonGreaseCipherSuites = {0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> samsung_internet29_android16_galaxy_s25plusSupportedGroups = {0x1A1A, 0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> samsung_internet29_android16_galaxy_s25plusNonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> samsung_internet29_android16_galaxy_s25plusExtensionOrder = {0x7A7A, 0x001B, 0x0000, 0x0017, 0xFF01, 0x002B, 0xFE0D, 0x0023, 0x0033, 0x000B, 0x000A, 0x000D, 0x0012, 0x0010, 0x002D, 0x0005, 0x6A6A};
inline const vector<uint16> samsung_internet29_android16_galaxy_s25plusNonGreaseExtensionsWithoutPadding = {0x001B, 0x0000, 0x0017, 0xFF01, 0x002B, 0xFE0D, 0x0023, 0x0033, 0x000B, 0x000A, 0x000D, 0x0012, 0x0010, 0x002D, 0x0005};
inline const vector<string> samsung_internet29_android16_galaxy_s25plusAlpnProtocols = {"http/1.1"};
inline const vector<uint16> samsung_internet29_android16_galaxy_s25plusCompressCertificateAlgorithms = {0x0002};
inline const vector<KeyShareExpectation> samsung_internet29_android16_galaxy_s25plusKeyShareEntries = {{0x1A1A, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation samsung_internet29_android16_galaxy_s25plusEch{true, 0x00, 0x0001, 0x0001, 32, 208};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/android/yandex26_3_4_128_oxygenos16_oneplus13.clienthello.json
// fixture_id=yandex26_3_4_128_oxygenos16_oneplus13:frame76
inline constexpr const char yandex26_3_4_128_oxygenos16_oneplus13FixtureId[] = "yandex26_3_4_128_oxygenos16_oneplus13:frame76";
inline constexpr const char yandex26_3_4_128_oxygenos16_oneplus13SourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/Android/Яндекс.Браузер 26.3.4.128 (OxygenOS 16, аппарат Oneplus 13).pcap";
inline constexpr const char yandex26_3_4_128_oxygenos16_oneplus13SourceSha256[] = "e28bf623f21453a9f0fd0c1a2bd01e737f8dccc4336fb977a07b55d93fa2c735";
inline constexpr const char yandex26_3_4_128_oxygenos16_oneplus13CaptureDateUtc[] = "2026-04-07T12:56:54Z";
inline constexpr const char yandex26_3_4_128_oxygenos16_oneplus13ParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char yandex26_3_4_128_oxygenos16_oneplus13ScenarioId[] = "android_oxygenos16_oneplus13_yandex26_3_4_128_clienthello";
inline constexpr const char yandex26_3_4_128_oxygenos16_oneplus13RouteMode[] = "non_ru_egress";
inline constexpr const char yandex26_3_4_128_oxygenos16_oneplus13Sni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 yandex26_3_4_128_oxygenos16_oneplus13FrameNumber = 76;
inline constexpr uint32 yandex26_3_4_128_oxygenos16_oneplus13TcpStream = 1;
inline constexpr uint16 yandex26_3_4_128_oxygenos16_oneplus13RecordLength = 1814;
inline constexpr uint16 yandex26_3_4_128_oxygenos16_oneplus13HandshakeLength = 1810;
inline const vector<uint16> yandex26_3_4_128_oxygenos16_oneplus13CipherSuites = {0x1A1A, 0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> yandex26_3_4_128_oxygenos16_oneplus13NonGreaseCipherSuites = {0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> yandex26_3_4_128_oxygenos16_oneplus13SupportedGroups = {0x9A9A, 0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> yandex26_3_4_128_oxygenos16_oneplus13NonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> yandex26_3_4_128_oxygenos16_oneplus13ExtensionOrder = {0x0A0A, 0xFE0D, 0x001B, 0x0023, 0x002B, 0xFF01, 0x0005, 0x000A, 0x0012, 0x0010, 0x002D, 0x0033, 0x0000, 0x000B, 0x0017, 0x000D, 0xAAAA};
inline const vector<uint16> yandex26_3_4_128_oxygenos16_oneplus13NonGreaseExtensionsWithoutPadding = {0xFE0D, 0x001B, 0x0023, 0x002B, 0xFF01, 0x0005, 0x000A, 0x0012, 0x0010, 0x002D, 0x0033, 0x0000, 0x000B, 0x0017, 0x000D};
inline const vector<string> yandex26_3_4_128_oxygenos16_oneplus13AlpnProtocols = {"http/1.1"};
inline const vector<uint16> yandex26_3_4_128_oxygenos16_oneplus13CompressCertificateAlgorithms = {0x0002};
inline const vector<KeyShareExpectation> yandex26_3_4_128_oxygenos16_oneplus13KeyShareEntries = {{0x9A9A, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation yandex26_3_4_128_oxygenos16_oneplus13Ech{true, 0x00, 0x0001, 0x0001, 32, 240};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/android/yandex26_3_4_android16_samsung.clienthello.json
// fixture_id=yandex26_3_4_android16_samsung:frame174
inline constexpr const char yandex26_3_4_android16_samsungFixtureId[] = "yandex26_3_4_android16_samsung:frame174";
inline constexpr const char yandex26_3_4_android16_samsungSourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/Android/Андроид 16 (самсунг), Яндекс браузер 26.3.4.pcap";
inline constexpr const char yandex26_3_4_android16_samsungSourceSha256[] = "dbc2251539cdc02565786dcd4dc736330665510324350069430ccd8c4002cfd2";
inline constexpr const char yandex26_3_4_android16_samsungCaptureDateUtc[] = "2026-04-07T14:05:31Z";
inline constexpr const char yandex26_3_4_android16_samsungParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char yandex26_3_4_android16_samsungScenarioId[] = "android16_samsung_yandex26_3_4_clienthello";
inline constexpr const char yandex26_3_4_android16_samsungRouteMode[] = "non_ru_egress";
inline constexpr const char yandex26_3_4_android16_samsungSni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 yandex26_3_4_android16_samsungFrameNumber = 174;
inline constexpr uint32 yandex26_3_4_android16_samsungTcpStream = 2;
inline constexpr uint16 yandex26_3_4_android16_samsungRecordLength = 1946;
inline constexpr uint16 yandex26_3_4_android16_samsungHandshakeLength = 1942;
inline const vector<uint16> yandex26_3_4_android16_samsungCipherSuites = {0x2A2A, 0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> yandex26_3_4_android16_samsungNonGreaseCipherSuites = {0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> yandex26_3_4_android16_samsungSupportedGroups = {0xBABA, 0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> yandex26_3_4_android16_samsungNonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> yandex26_3_4_android16_samsungExtensionOrder = {0x6A6A, 0x0017, 0x000D, 0x0000, 0x000B, 0x002D, 0x001B, 0x0010, 0xFF01, 0x0023, 0x002B, 0x0012, 0x0005, 0x44CD, 0x000A, 0xFE0D, 0x0033, 0x4A4A, 0x0029};
inline const vector<uint16> yandex26_3_4_android16_samsungNonGreaseExtensionsWithoutPadding = {0x0017, 0x000D, 0x0000, 0x000B, 0x002D, 0x001B, 0x0010, 0xFF01, 0x0023, 0x002B, 0x0012, 0x0005, 0x44CD, 0x000A, 0xFE0D, 0x0033, 0x0029};
inline const vector<string> yandex26_3_4_android16_samsungAlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> yandex26_3_4_android16_samsungCompressCertificateAlgorithms = {0x0002};
inline const vector<KeyShareExpectation> yandex26_3_4_android16_samsungKeyShareEntries = {{0xBABA, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation yandex26_3_4_android16_samsungEch{true, 0x00, 0x0001, 0x0001, 32, 208};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/ios/brave188_ios26_4.clienthello.json
// fixture_id=brave188_ios26_4:frame38
inline constexpr const char brave188_ios26_4FixtureId[] = "brave188_ios26_4:frame38";
inline constexpr const char brave188_ios26_4SourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/iOS/Brave 1.88, iOS 26.4.pcap";
inline constexpr const char brave188_ios26_4SourceSha256[] = "beba6d4de133035c6dd6bb86578a01e4b97432eda5ec0adc1b76056251b9646e";
inline constexpr const char brave188_ios26_4CaptureDateUtc[] = "2026-04-07T13:08:58Z";
inline constexpr const char brave188_ios26_4ParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char brave188_ios26_4ScenarioId[] = "ios26_4_brave188_clienthello";
inline constexpr const char brave188_ios26_4RouteMode[] = "non_ru_egress";
inline constexpr const char brave188_ios26_4Sni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 brave188_ios26_4FrameNumber = 38;
inline constexpr uint32 brave188_ios26_4TcpStream = 2;
inline constexpr uint16 brave188_ios26_4RecordLength = 1543;
inline constexpr uint16 brave188_ios26_4HandshakeLength = 1539;
inline const vector<uint16> brave188_ios26_4CipherSuites = {0x8A8A, 0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> brave188_ios26_4NonGreaseCipherSuites = {0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> brave188_ios26_4SupportedGroups = {0x3A3A, 0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> brave188_ios26_4NonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> brave188_ios26_4ExtensionOrder = {0xDADA, 0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B, 0xEAEA};
inline const vector<uint16> brave188_ios26_4NonGreaseExtensionsWithoutPadding = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B};
inline const vector<string> brave188_ios26_4AlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> brave188_ios26_4CompressCertificateAlgorithms = {0x0001};
inline const vector<KeyShareExpectation> brave188_ios26_4KeyShareEntries = {{0x3A3A, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation brave188_ios26_4Ech{false, 0, 0, 0, 0, 0};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/ios/chrome146_0_7680_151_ios26_1.clienthello.json
// fixture_id=chrome146_0_7680_151_ios26_1:frame40
inline constexpr const char chrome146_0_7680_151_ios26_1FixtureId[] = "chrome146_0_7680_151_ios26_1:frame40";
inline constexpr const char chrome146_0_7680_151_ios26_1SourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/iOS/IOS 26.1 Chrome 146.0.7680.151.pcap";
inline constexpr const char chrome146_0_7680_151_ios26_1SourceSha256[] = "0ba1a10b1ef5c16e6cc1c96384664a48db0c8137c2e795dff36a09981f48fd58";
inline constexpr const char chrome146_0_7680_151_ios26_1CaptureDateUtc[] = "2026-04-07T13:17:50Z";
inline constexpr const char chrome146_0_7680_151_ios26_1ParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char chrome146_0_7680_151_ios26_1ScenarioId[] = "ios26_1_chrome146_0_7680_151_clienthello";
inline constexpr const char chrome146_0_7680_151_ios26_1RouteMode[] = "non_ru_egress";
inline constexpr const char chrome146_0_7680_151_ios26_1Sni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 chrome146_0_7680_151_ios26_1FrameNumber = 40;
inline constexpr uint32 chrome146_0_7680_151_ios26_1TcpStream = 1;
inline constexpr uint16 chrome146_0_7680_151_ios26_1RecordLength = 1978;
inline constexpr uint16 chrome146_0_7680_151_ios26_1HandshakeLength = 1974;
inline const vector<uint16> chrome146_0_7680_151_ios26_1CipherSuites = {0xDADA, 0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome146_0_7680_151_ios26_1NonGreaseCipherSuites = {0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome146_0_7680_151_ios26_1SupportedGroups = {0x0A0A, 0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome146_0_7680_151_ios26_1NonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome146_0_7680_151_ios26_1ExtensionOrder = {0x1A1A, 0x0005, 0x0033, 0x002D, 0x000D, 0x000B, 0x0017, 0x002B, 0xFE0D, 0x0000, 0x0023, 0x000A, 0x0012, 0xFF01, 0x001B, 0x44CD, 0x0010, 0xDADA, 0x0029};
inline const vector<uint16> chrome146_0_7680_151_ios26_1NonGreaseExtensionsWithoutPadding = {0x0005, 0x0033, 0x002D, 0x000D, 0x000B, 0x0017, 0x002B, 0xFE0D, 0x0000, 0x0023, 0x000A, 0x0012, 0xFF01, 0x001B, 0x44CD, 0x0010, 0x0029};
inline const vector<string> chrome146_0_7680_151_ios26_1AlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> chrome146_0_7680_151_ios26_1CompressCertificateAlgorithms = {0x0002};
inline const vector<KeyShareExpectation> chrome146_0_7680_151_ios26_1KeyShareEntries = {{0x0A0A, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation chrome146_0_7680_151_ios26_1Ech{true, 0x00, 0x0001, 0x0001, 32, 240};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/ios/chrome147_0_7727_47_ios26_3.clienthello.json
// fixture_id=chrome147_0_7727_47_ios26_3:frame27
inline constexpr const char chrome147_0_7727_47_ios26_3FixtureId[] = "chrome147_0_7727_47_ios26_3:frame27";
inline constexpr const char chrome147_0_7727_47_ios26_3SourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/iOS/iOS 26.3, Chrome 147.0.7727.47.pcap";
inline constexpr const char chrome147_0_7727_47_ios26_3SourceSha256[] = "b7c3a12c9903066475ef4cbc5799e646f2740f41b77e2396f8b8cbea3cb4ecaa";
inline constexpr const char chrome147_0_7727_47_ios26_3CaptureDateUtc[] = "2026-04-07T13:17:02Z";
inline constexpr const char chrome147_0_7727_47_ios26_3ParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char chrome147_0_7727_47_ios26_3ScenarioId[] = "ios26_3_chrome147_0_7727_47_clienthello";
inline constexpr const char chrome147_0_7727_47_ios26_3RouteMode[] = "non_ru_egress";
inline constexpr const char chrome147_0_7727_47_ios26_3Sni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 chrome147_0_7727_47_ios26_3FrameNumber = 27;
inline constexpr uint32 chrome147_0_7727_47_ios26_3TcpStream = 1;
inline constexpr uint16 chrome147_0_7727_47_ios26_3RecordLength = 1882;
inline constexpr uint16 chrome147_0_7727_47_ios26_3HandshakeLength = 1878;
inline const vector<uint16> chrome147_0_7727_47_ios26_3CipherSuites = {0xDADA, 0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome147_0_7727_47_ios26_3NonGreaseCipherSuites = {0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome147_0_7727_47_ios26_3SupportedGroups = {0xFAFA, 0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome147_0_7727_47_ios26_3NonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome147_0_7727_47_ios26_3ExtensionOrder = {0x9A9A, 0xFF01, 0x0033, 0x000B, 0x0023, 0x0005, 0xFE0D, 0x0010, 0x0012, 0x0017, 0x44CD, 0x002D, 0x000D, 0x0000, 0x001B, 0x002B, 0x000A, 0xDADA, 0x0029};
inline const vector<uint16> chrome147_0_7727_47_ios26_3NonGreaseExtensionsWithoutPadding = {0xFF01, 0x0033, 0x000B, 0x0023, 0x0005, 0xFE0D, 0x0010, 0x0012, 0x0017, 0x44CD, 0x002D, 0x000D, 0x0000, 0x001B, 0x002B, 0x000A, 0x0029};
inline const vector<string> chrome147_0_7727_47_ios26_3AlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> chrome147_0_7727_47_ios26_3CompressCertificateAlgorithms = {0x0002};
inline const vector<KeyShareExpectation> chrome147_0_7727_47_ios26_3KeyShareEntries = {{0xFAFA, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation chrome147_0_7727_47_ios26_3Ech{true, 0x00, 0x0001, 0x0001, 32, 144};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/ios/chrome147_0_7727_47_ios26_4_a.clienthello.json
// fixture_id=chrome147_0_7727_47_ios26_4_a:frame148
inline constexpr const char chrome147_0_7727_47_ios26_4_aFixtureId[] = "chrome147_0_7727_47_ios26_4_a:frame148";
inline constexpr const char chrome147_0_7727_47_ios26_4_aSourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/iOS/iOS 26.4, Google Chrome 147.0.7727.47.pcap";
inline constexpr const char chrome147_0_7727_47_ios26_4_aSourceSha256[] = "1cf4bb2f0c28ad96d260082687c900e8fcccaba845b411c2c819fd5760251259";
inline constexpr const char chrome147_0_7727_47_ios26_4_aCaptureDateUtc[] = "2026-04-07T13:14:16Z";
inline constexpr const char chrome147_0_7727_47_ios26_4_aParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char chrome147_0_7727_47_ios26_4_aScenarioId[] = "ios26_4_chrome147_0_7727_47_a_clienthello";
inline constexpr const char chrome147_0_7727_47_ios26_4_aRouteMode[] = "non_ru_egress";
inline constexpr const char chrome147_0_7727_47_ios26_4_aSni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 chrome147_0_7727_47_ios26_4_aFrameNumber = 148;
inline constexpr uint32 chrome147_0_7727_47_ios26_4_aTcpStream = 2;
inline constexpr uint16 chrome147_0_7727_47_ios26_4_aRecordLength = 1540;
inline constexpr uint16 chrome147_0_7727_47_ios26_4_aHandshakeLength = 1536;
inline const vector<uint16> chrome147_0_7727_47_ios26_4_aCipherSuites = {0xDADA, 0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> chrome147_0_7727_47_ios26_4_aNonGreaseCipherSuites = {0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> chrome147_0_7727_47_ios26_4_aSupportedGroups = {0x4A4A, 0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> chrome147_0_7727_47_ios26_4_aNonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> chrome147_0_7727_47_ios26_4_aExtensionOrder = {0x0A0A, 0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B, 0xDADA};
inline const vector<uint16> chrome147_0_7727_47_ios26_4_aNonGreaseExtensionsWithoutPadding = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B};
inline const vector<string> chrome147_0_7727_47_ios26_4_aAlpnProtocols = {"http/1.1"};
inline const vector<uint16> chrome147_0_7727_47_ios26_4_aCompressCertificateAlgorithms = {0x0001};
inline const vector<KeyShareExpectation> chrome147_0_7727_47_ios26_4_aKeyShareEntries = {{0x4A4A, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation chrome147_0_7727_47_ios26_4_aEch{false, 0, 0, 0, 0, 0};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/ios/chrome147_0_7727_47_ios26_4_b.clienthello.json
// fixture_id=chrome147_0_7727_47_ios26_4_b:frame161
inline constexpr const char chrome147_0_7727_47_ios26_4_bFixtureId[] = "chrome147_0_7727_47_ios26_4_b:frame161";
inline constexpr const char chrome147_0_7727_47_ios26_4_bSourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/iOS/ios 26.4,Chrome 147.0.7727.47.pcap";
inline constexpr const char chrome147_0_7727_47_ios26_4_bSourceSha256[] = "c36b11658ac5b5217efba304fcd00c8c97e7e4830b4ef61faa402a9f105714c5";
inline constexpr const char chrome147_0_7727_47_ios26_4_bCaptureDateUtc[] = "2026-04-07T13:05:18Z";
inline constexpr const char chrome147_0_7727_47_ios26_4_bParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char chrome147_0_7727_47_ios26_4_bScenarioId[] = "ios26_4_chrome147_0_7727_47_b_clienthello";
inline constexpr const char chrome147_0_7727_47_ios26_4_bRouteMode[] = "non_ru_egress";
inline constexpr const char chrome147_0_7727_47_ios26_4_bSni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 chrome147_0_7727_47_ios26_4_bFrameNumber = 161;
inline constexpr uint32 chrome147_0_7727_47_ios26_4_bTcpStream = 2;
inline constexpr uint16 chrome147_0_7727_47_ios26_4_bRecordLength = 1543;
inline constexpr uint16 chrome147_0_7727_47_ios26_4_bHandshakeLength = 1539;
inline const vector<uint16> chrome147_0_7727_47_ios26_4_bCipherSuites = {0xBABA, 0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> chrome147_0_7727_47_ios26_4_bNonGreaseCipherSuites = {0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> chrome147_0_7727_47_ios26_4_bSupportedGroups = {0xFAFA, 0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> chrome147_0_7727_47_ios26_4_bNonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> chrome147_0_7727_47_ios26_4_bExtensionOrder = {0x5A5A, 0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B, 0x7A7A};
inline const vector<uint16> chrome147_0_7727_47_ios26_4_bNonGreaseExtensionsWithoutPadding = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B};
inline const vector<string> chrome147_0_7727_47_ios26_4_bAlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> chrome147_0_7727_47_ios26_4_bCompressCertificateAlgorithms = {0x0001};
inline const vector<KeyShareExpectation> chrome147_0_7727_47_ios26_4_bKeyShareEntries = {{0xFAFA, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation chrome147_0_7727_47_ios26_4_bEch{false, 0, 0, 0, 0, 0};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/ios/firefox149_2_ios26_4.clienthello.json
// fixture_id=firefox149_2_ios26_4:frame126
inline constexpr const char firefox149_2_ios26_4FixtureId[] = "firefox149_2_ios26_4:frame126";
inline constexpr const char firefox149_2_ios26_4SourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/iOS/iOS 26.4 Firefox 149.2 (69775).pcap";
inline constexpr const char firefox149_2_ios26_4SourceSha256[] = "5bf18e72a6f38b8c314d1b62416d26bd8d8331c811526e23f3ebd8c3fdcc77ef";
inline constexpr const char firefox149_2_ios26_4CaptureDateUtc[] = "2026-04-07T13:16:57Z";
inline constexpr const char firefox149_2_ios26_4ParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char firefox149_2_ios26_4ScenarioId[] = "ios26_4_firefox149_2_clienthello";
inline constexpr const char firefox149_2_ios26_4RouteMode[] = "non_ru_egress";
inline constexpr const char firefox149_2_ios26_4Sni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 firefox149_2_ios26_4FrameNumber = 126;
inline constexpr uint32 firefox149_2_ios26_4TcpStream = 3;
inline constexpr uint16 firefox149_2_ios26_4RecordLength = 1543;
inline constexpr uint16 firefox149_2_ios26_4HandshakeLength = 1539;
inline const vector<uint16> firefox149_2_ios26_4CipherSuites = {0x0A0A, 0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> firefox149_2_ios26_4NonGreaseCipherSuites = {0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> firefox149_2_ios26_4SupportedGroups = {0xDADA, 0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> firefox149_2_ios26_4NonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> firefox149_2_ios26_4ExtensionOrder = {0x2A2A, 0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B, 0xDADA};
inline const vector<uint16> firefox149_2_ios26_4NonGreaseExtensionsWithoutPadding = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B};
inline const vector<string> firefox149_2_ios26_4AlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> firefox149_2_ios26_4CompressCertificateAlgorithms = {0x0001};
inline const vector<KeyShareExpectation> firefox149_2_ios26_4KeyShareEntries = {{0xDADA, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation firefox149_2_ios26_4Ech{false, 0, 0, 0, 0, 0};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/ios/safari18_7_6_ios18_7_6.clienthello.json
// fixture_id=safari18_7_6_ios18_7_6:frame184
inline constexpr const char safari18_7_6_ios18_7_6FixtureId[] = "safari18_7_6_ios18_7_6:frame184";
inline constexpr const char safari18_7_6_ios18_7_6SourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/iOS/iOS 18.7.6. Safari 18.7.6.pcap";
inline constexpr const char safari18_7_6_ios18_7_6SourceSha256[] = "33e9c4d9299875bd07b22d41602e58c448fe5457e5e960fd113f337401ff5759";
inline constexpr const char safari18_7_6_ios18_7_6CaptureDateUtc[] = "2026-04-07T12:52:31Z";
inline constexpr const char safari18_7_6_ios18_7_6ParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char safari18_7_6_ios18_7_6ScenarioId[] = "ios18_7_6_safari18_7_6_clienthello";
inline constexpr const char safari18_7_6_ios18_7_6RouteMode[] = "non_ru_egress";
inline constexpr const char safari18_7_6_ios18_7_6Sni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 safari18_7_6_ios18_7_6FrameNumber = 184;
inline constexpr uint32 safari18_7_6_ios18_7_6TcpStream = 5;
inline constexpr uint16 safari18_7_6_ios18_7_6RecordLength = 512;
inline constexpr uint16 safari18_7_6_ios18_7_6HandshakeLength = 508;
inline const vector<uint16> safari18_7_6_ios18_7_6CipherSuites = {0x3A3A, 0x1301, 0x1302, 0x1303, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> safari18_7_6_ios18_7_6NonGreaseCipherSuites = {0x1301, 0x1302, 0x1303, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> safari18_7_6_ios18_7_6SupportedGroups = {0x3A3A, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> safari18_7_6_ios18_7_6NonGreaseSupportedGroups = {0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> safari18_7_6_ios18_7_6ExtensionOrder = {0xFAFA, 0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B, 0x8A8A, 0x0015};
inline const vector<uint16> safari18_7_6_ios18_7_6NonGreaseExtensionsWithoutPadding = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B};
inline const vector<string> safari18_7_6_ios18_7_6AlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> safari18_7_6_ios18_7_6CompressCertificateAlgorithms = {0x0001};
inline const vector<KeyShareExpectation> safari18_7_6_ios18_7_6KeyShareEntries = {{0x3A3A, 1, true}, {0x001D, 32, false}};
inline constexpr EchExpectation safari18_7_6_ios18_7_6Ech{false, 0, 0, 0, 0, 0};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/ios/safari26_2_ios26_2_a.clienthello.json
// fixture_id=safari26_2_ios26_2_a:frame24
inline constexpr const char safari26_2_ios26_2_aFixtureId[] = "safari26_2_ios26_2_a:frame24";
inline constexpr const char safari26_2_ios26_2_aSourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/iOS/iOS 26.2, Safari 26.2.pcap";
inline constexpr const char safari26_2_ios26_2_aSourceSha256[] = "bdc2edef5881b62869711a5c8b3cf7bf692a17060a434906f2e7db3e999d53b4";
inline constexpr const char safari26_2_ios26_2_aCaptureDateUtc[] = "2026-04-07T13:58:43Z";
inline constexpr const char safari26_2_ios26_2_aParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char safari26_2_ios26_2_aScenarioId[] = "ios26_2_safari26_2_a_clienthello";
inline constexpr const char safari26_2_ios26_2_aRouteMode[] = "non_ru_egress";
inline constexpr const char safari26_2_ios26_2_aSni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 safari26_2_ios26_2_aFrameNumber = 24;
inline constexpr uint32 safari26_2_ios26_2_aTcpStream = 3;
inline constexpr uint16 safari26_2_ios26_2_aRecordLength = 1543;
inline constexpr uint16 safari26_2_ios26_2_aHandshakeLength = 1539;
inline const vector<uint16> safari26_2_ios26_2_aCipherSuites = {0x9A9A, 0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> safari26_2_ios26_2_aNonGreaseCipherSuites = {0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> safari26_2_ios26_2_aSupportedGroups = {0x0A0A, 0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> safari26_2_ios26_2_aNonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> safari26_2_ios26_2_aExtensionOrder = {0xAAAA, 0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B, 0xEAEA};
inline const vector<uint16> safari26_2_ios26_2_aNonGreaseExtensionsWithoutPadding = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B};
inline const vector<string> safari26_2_ios26_2_aAlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> safari26_2_ios26_2_aCompressCertificateAlgorithms = {0x0001};
inline const vector<KeyShareExpectation> safari26_2_ios26_2_aKeyShareEntries = {{0x0A0A, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation safari26_2_ios26_2_aEch{false, 0, 0, 0, 0, 0};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/ios/safari26_2_ios26_2_b.clienthello.json
// fixture_id=safari26_2_ios26_2_b:frame18
inline constexpr const char safari26_2_ios26_2_bFixtureId[] = "safari26_2_ios26_2_b:frame18";
inline constexpr const char safari26_2_ios26_2_bSourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/iOS/ios 26.2, Safari 26.2 (2).pcap";
inline constexpr const char safari26_2_ios26_2_bSourceSha256[] = "7512870f9776910b71f8eb30a7fd8b726724f22db22f5371fe36320a9a9c68a4";
inline constexpr const char safari26_2_ios26_2_bCaptureDateUtc[] = "2026-04-07T14:12:24Z";
inline constexpr const char safari26_2_ios26_2_bParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char safari26_2_ios26_2_bScenarioId[] = "ios26_2_safari26_2_b_clienthello";
inline constexpr const char safari26_2_ios26_2_bRouteMode[] = "non_ru_egress";
inline constexpr const char safari26_2_ios26_2_bSni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 safari26_2_ios26_2_bFrameNumber = 18;
inline constexpr uint32 safari26_2_ios26_2_bTcpStream = 1;
inline constexpr uint16 safari26_2_ios26_2_bRecordLength = 1543;
inline constexpr uint16 safari26_2_ios26_2_bHandshakeLength = 1539;
inline const vector<uint16> safari26_2_ios26_2_bCipherSuites = {0x0A0A, 0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> safari26_2_ios26_2_bNonGreaseCipherSuites = {0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> safari26_2_ios26_2_bSupportedGroups = {0x2A2A, 0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> safari26_2_ios26_2_bNonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> safari26_2_ios26_2_bExtensionOrder = {0x5A5A, 0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B, 0x2A2A};
inline const vector<uint16> safari26_2_ios26_2_bNonGreaseExtensionsWithoutPadding = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B};
inline const vector<string> safari26_2_ios26_2_bAlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> safari26_2_ios26_2_bCompressCertificateAlgorithms = {0x0001};
inline const vector<KeyShareExpectation> safari26_2_ios26_2_bKeyShareEntries = {{0x2A2A, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation safari26_2_ios26_2_bEch{false, 0, 0, 0, 0, 0};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/ios/safari26_3_1_ios26_3_1_a.clienthello.json
// fixture_id=safari26_3_1_ios26_3_1_a:frame76
inline constexpr const char safari26_3_1_ios26_3_1_aFixtureId[] = "safari26_3_1_ios26_3_1_a:frame76";
inline constexpr const char safari26_3_1_ios26_3_1_aSourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/iOS/Ios 26.3.1, Safari 26.3.1.pcap";
inline constexpr const char safari26_3_1_ios26_3_1_aSourceSha256[] = "4d463a3c4a8fec67c184c536dedf063441a61c70303aba3ead72e7524e7e840f";
inline constexpr const char safari26_3_1_ios26_3_1_aCaptureDateUtc[] = "2026-04-07T13:42:45Z";
inline constexpr const char safari26_3_1_ios26_3_1_aParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char safari26_3_1_ios26_3_1_aScenarioId[] = "ios26_3_1_safari26_3_1_a_clienthello";
inline constexpr const char safari26_3_1_ios26_3_1_aRouteMode[] = "non_ru_egress";
inline constexpr const char safari26_3_1_ios26_3_1_aSni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 safari26_3_1_ios26_3_1_aFrameNumber = 76;
inline constexpr uint32 safari26_3_1_ios26_3_1_aTcpStream = 1;
inline constexpr uint16 safari26_3_1_ios26_3_1_aRecordLength = 1543;
inline constexpr uint16 safari26_3_1_ios26_3_1_aHandshakeLength = 1539;
inline const vector<uint16> safari26_3_1_ios26_3_1_aCipherSuites = {0x9A9A, 0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> safari26_3_1_ios26_3_1_aNonGreaseCipherSuites = {0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> safari26_3_1_ios26_3_1_aSupportedGroups = {0x4A4A, 0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> safari26_3_1_ios26_3_1_aNonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> safari26_3_1_ios26_3_1_aExtensionOrder = {0x7A7A, 0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B, 0x8A8A};
inline const vector<uint16> safari26_3_1_ios26_3_1_aNonGreaseExtensionsWithoutPadding = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B};
inline const vector<string> safari26_3_1_ios26_3_1_aAlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> safari26_3_1_ios26_3_1_aCompressCertificateAlgorithms = {0x0001};
inline const vector<KeyShareExpectation> safari26_3_1_ios26_3_1_aKeyShareEntries = {{0x4A4A, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation safari26_3_1_ios26_3_1_aEch{false, 0, 0, 0, 0, 0};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/ios/safari26_3_1_ios26_3_1_b.clienthello.json
// fixture_id=safari26_3_1_ios26_3_1_b:frame66
inline constexpr const char safari26_3_1_ios26_3_1_bFixtureId[] = "safari26_3_1_ios26_3_1_b:frame66";
inline constexpr const char safari26_3_1_ios26_3_1_bSourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/iOS/Ios 26.3.1, Safari  26.3.1 (2).pcap";
inline constexpr const char safari26_3_1_ios26_3_1_bSourceSha256[] = "1f751d1226a2bbd706f50d35a61e8b5b8bcb857d8cbd1c8aa2a649367477198a";
inline constexpr const char safari26_3_1_ios26_3_1_bCaptureDateUtc[] = "2026-04-07T13:42:25Z";
inline constexpr const char safari26_3_1_ios26_3_1_bParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char safari26_3_1_ios26_3_1_bScenarioId[] = "ios26_3_1_safari26_3_1_b_clienthello";
inline constexpr const char safari26_3_1_ios26_3_1_bRouteMode[] = "non_ru_egress";
inline constexpr const char safari26_3_1_ios26_3_1_bSni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 safari26_3_1_ios26_3_1_bFrameNumber = 66;
inline constexpr uint32 safari26_3_1_ios26_3_1_bTcpStream = 1;
inline constexpr uint16 safari26_3_1_ios26_3_1_bRecordLength = 1543;
inline constexpr uint16 safari26_3_1_ios26_3_1_bHandshakeLength = 1539;
inline const vector<uint16> safari26_3_1_ios26_3_1_bCipherSuites = {0x8A8A, 0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> safari26_3_1_ios26_3_1_bNonGreaseCipherSuites = {0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> safari26_3_1_ios26_3_1_bSupportedGroups = {0xCACA, 0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> safari26_3_1_ios26_3_1_bNonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> safari26_3_1_ios26_3_1_bExtensionOrder = {0x4A4A, 0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B, 0xCACA};
inline const vector<uint16> safari26_3_1_ios26_3_1_bNonGreaseExtensionsWithoutPadding = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B};
inline const vector<string> safari26_3_1_ios26_3_1_bAlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> safari26_3_1_ios26_3_1_bCompressCertificateAlgorithms = {0x0001};
inline const vector<KeyShareExpectation> safari26_3_1_ios26_3_1_bKeyShareEntries = {{0xCACA, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation safari26_3_1_ios26_3_1_bEch{false, 0, 0, 0, 0, 0};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/ios/safari26_4_ios26_4_a.clienthello.json
// fixture_id=safari26_4_ios26_4_a:frame18
inline constexpr const char safari26_4_ios26_4_aFixtureId[] = "safari26_4_ios26_4_a:frame18";
inline constexpr const char safari26_4_ios26_4_aSourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/iOS/Safari 26.4, iOS 26.4.pcap";
inline constexpr const char safari26_4_ios26_4_aSourceSha256[] = "b07109df80dca8a8bdacf98572f057e00893fcc8ed73820c54922949dbed3cf9";
inline constexpr const char safari26_4_ios26_4_aCaptureDateUtc[] = "2026-04-07T13:01:45Z";
inline constexpr const char safari26_4_ios26_4_aParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char safari26_4_ios26_4_aScenarioId[] = "ios26_4_safari26_4_a_clienthello";
inline constexpr const char safari26_4_ios26_4_aRouteMode[] = "non_ru_egress";
inline constexpr const char safari26_4_ios26_4_aSni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 safari26_4_ios26_4_aFrameNumber = 18;
inline constexpr uint32 safari26_4_ios26_4_aTcpStream = 1;
inline constexpr uint16 safari26_4_ios26_4_aRecordLength = 1543;
inline constexpr uint16 safari26_4_ios26_4_aHandshakeLength = 1539;
inline const vector<uint16> safari26_4_ios26_4_aCipherSuites = {0xFAFA, 0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> safari26_4_ios26_4_aNonGreaseCipherSuites = {0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> safari26_4_ios26_4_aSupportedGroups = {0x7A7A, 0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> safari26_4_ios26_4_aNonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> safari26_4_ios26_4_aExtensionOrder = {0xAAAA, 0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B, 0xBABA};
inline const vector<uint16> safari26_4_ios26_4_aNonGreaseExtensionsWithoutPadding = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B};
inline const vector<string> safari26_4_ios26_4_aAlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> safari26_4_ios26_4_aCompressCertificateAlgorithms = {0x0001};
inline const vector<KeyShareExpectation> safari26_4_ios26_4_aKeyShareEntries = {{0x7A7A, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation safari26_4_ios26_4_aEch{false, 0, 0, 0, 0, 0};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/ios/safari26_4_ios26_4_b.clienthello.json
// fixture_id=safari26_4_ios26_4_b:frame21
inline constexpr const char safari26_4_ios26_4_bFixtureId[] = "safari26_4_ios26_4_b:frame21";
inline constexpr const char safari26_4_ios26_4_bSourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/iOS/iOS 26.4, Safari 26.4 (2).pcap";
inline constexpr const char safari26_4_ios26_4_bSourceSha256[] = "a5d526c2112ba8ad4b372759114eabc3f9e6a3aba4e1115d8a0afcc9145f85a6";
inline constexpr const char safari26_4_ios26_4_bCaptureDateUtc[] = "2026-04-07T13:57:15Z";
inline constexpr const char safari26_4_ios26_4_bParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char safari26_4_ios26_4_bScenarioId[] = "ios26_4_safari26_4_b_clienthello";
inline constexpr const char safari26_4_ios26_4_bRouteMode[] = "non_ru_egress";
inline constexpr const char safari26_4_ios26_4_bSni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 safari26_4_ios26_4_bFrameNumber = 21;
inline constexpr uint32 safari26_4_ios26_4_bTcpStream = 1;
inline constexpr uint16 safari26_4_ios26_4_bRecordLength = 1543;
inline constexpr uint16 safari26_4_ios26_4_bHandshakeLength = 1539;
inline const vector<uint16> safari26_4_ios26_4_bCipherSuites = {0xCACA, 0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> safari26_4_ios26_4_bNonGreaseCipherSuites = {0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> safari26_4_ios26_4_bSupportedGroups = {0x4A4A, 0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> safari26_4_ios26_4_bNonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> safari26_4_ios26_4_bExtensionOrder = {0x1A1A, 0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B, 0xFAFA};
inline const vector<uint16> safari26_4_ios26_4_bNonGreaseExtensionsWithoutPadding = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B};
inline const vector<string> safari26_4_ios26_4_bAlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> safari26_4_ios26_4_bCompressCertificateAlgorithms = {0x0001};
inline const vector<KeyShareExpectation> safari26_4_ios26_4_bKeyShareEntries = {{0x4A4A, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation safari26_4_ios26_4_bEch{false, 0, 0, 0, 0, 0};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/ios/safari26_4_ios26_4_c.clienthello.json
// fixture_id=safari26_4_ios26_4_c:frame18
inline constexpr const char safari26_4_ios26_4_cFixtureId[] = "safari26_4_ios26_4_c:frame18";
inline constexpr const char safari26_4_ios26_4_cSourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/iOS/ios 26.4, safari 26.4.pcap";
inline constexpr const char safari26_4_ios26_4_cSourceSha256[] = "d679678896ab5d1055887d8a3d58f4fadc07ad0ddf84a8fd7c02e041cb37b710";
inline constexpr const char safari26_4_ios26_4_cCaptureDateUtc[] = "2026-04-07T13:42:28Z";
inline constexpr const char safari26_4_ios26_4_cParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char safari26_4_ios26_4_cScenarioId[] = "ios26_4_safari26_4_c_clienthello";
inline constexpr const char safari26_4_ios26_4_cRouteMode[] = "non_ru_egress";
inline constexpr const char safari26_4_ios26_4_cSni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 safari26_4_ios26_4_cFrameNumber = 18;
inline constexpr uint32 safari26_4_ios26_4_cTcpStream = 1;
inline constexpr uint16 safari26_4_ios26_4_cRecordLength = 1543;
inline constexpr uint16 safari26_4_ios26_4_cHandshakeLength = 1539;
inline const vector<uint16> safari26_4_ios26_4_cCipherSuites = {0x9A9A, 0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> safari26_4_ios26_4_cNonGreaseCipherSuites = {0x1302, 0x1303, 0x1301, 0xC02C, 0xC02B, 0xCCA9, 0xC030, 0xC02F, 0xCCA8, 0xC00A, 0xC009, 0xC014, 0xC013, 0x009D, 0x009C, 0x0035, 0x002F, 0xC008, 0xC012, 0x000A};
inline const vector<uint16> safari26_4_ios26_4_cSupportedGroups = {0xDADA, 0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> safari26_4_ios26_4_cNonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019};
inline const vector<uint16> safari26_4_ios26_4_cExtensionOrder = {0x5A5A, 0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B, 0x6A6A};
inline const vector<uint16> safari26_4_ios26_4_cNonGreaseExtensionsWithoutPadding = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x000D, 0x0012, 0x0033, 0x002D, 0x002B, 0x001B};
inline const vector<string> safari26_4_ios26_4_cAlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> safari26_4_ios26_4_cCompressCertificateAlgorithms = {0x0001};
inline const vector<KeyShareExpectation> safari26_4_ios26_4_cKeyShareEntries = {{0xDADA, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation safari26_4_ios26_4_cEch{false, 0, 0, 0, 0, 0};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/linux_desktop/chrome144_linux_desktop.clienthello.json
// fixture_id=chrome144_linux_desktop:frame5
inline constexpr const char chrome144_linux_desktopFixtureId[] = "chrome144_linux_desktop:frame5";
inline constexpr const char chrome144_linux_desktopSourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/Linux, desktop/clienthello-chrome144.0.7559.109-ubuntu24.04.pcapng";
inline constexpr const char chrome144_linux_desktopSourceSha256[] = "0b1f5304574735f6e3e87406d1f75f41d2b1823c898391c98da10d89a8008177";
inline constexpr const char chrome144_linux_desktopCaptureDateUtc[] = "2026-04-07T10:15:21Z";
inline constexpr const char chrome144_linux_desktopParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char chrome144_linux_desktopScenarioId[] = "linux_desktop_chrome144_clienthello";
inline constexpr const char chrome144_linux_desktopRouteMode[] = "non_ru_egress";
inline constexpr const char chrome144_linux_desktopSni[] = "viiita.fun";
inline constexpr uint32 chrome144_linux_desktopFrameNumber = 5;
inline constexpr uint32 chrome144_linux_desktopTcpStream = 0;
inline constexpr uint16 chrome144_linux_desktopRecordLength = 1779;
inline constexpr uint16 chrome144_linux_desktopHandshakeLength = 1775;
inline const vector<uint16> chrome144_linux_desktopCipherSuites = {0xCACA, 0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome144_linux_desktopNonGreaseCipherSuites = {0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome144_linux_desktopSupportedGroups = {0xDADA, 0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome144_linux_desktopNonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome144_linux_desktopExtensionOrder = {0xCACA, 0x000A, 0x0000, 0x002D, 0x0023, 0x000B, 0x002B, 0x0033, 0xFF01, 0xFE0D, 0x0010, 0x000D, 0x0017, 0x44CD, 0x001B, 0x0005, 0x0012, 0x2A2A};
inline const vector<uint16> chrome144_linux_desktopNonGreaseExtensionsWithoutPadding = {0x000A, 0x0000, 0x002D, 0x0023, 0x000B, 0x002B, 0x0033, 0xFF01, 0xFE0D, 0x0010, 0x000D, 0x0017, 0x44CD, 0x001B, 0x0005, 0x0012};
inline const vector<string> chrome144_linux_desktopAlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> chrome144_linux_desktopCompressCertificateAlgorithms = {0x0002};
inline const vector<KeyShareExpectation> chrome144_linux_desktopKeyShareEntries = {{0xDADA, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation chrome144_linux_desktopEch{true, 0x00, 0x0001, 0x0001, 32, 208};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/linux_desktop/chrome146_177_linux_desktop.clienthello.json
// fixture_id=chrome146_177_linux_desktop:frame5
inline constexpr const char chrome146_177_linux_desktopFixtureId[] = "chrome146_177_linux_desktop:frame5";
inline constexpr const char chrome146_177_linux_desktopSourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/Linux, desktop/chrome146.0.7680.177-1.pcapng";
inline constexpr const char chrome146_177_linux_desktopSourceSha256[] = "fca18c4290183273b647915300bd1e2ed353e29ff3acb0361c93153e03d95735";
inline constexpr const char chrome146_177_linux_desktopCaptureDateUtc[] = "2026-04-07T03:01:09Z";
inline constexpr const char chrome146_177_linux_desktopParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char chrome146_177_linux_desktopScenarioId[] = "linux_desktop_chrome146_177_clienthello";
inline constexpr const char chrome146_177_linux_desktopRouteMode[] = "non_ru_egress";
inline constexpr const char chrome146_177_linux_desktopSni[] = "viiita.fun";
inline constexpr uint32 chrome146_177_linux_desktopFrameNumber = 5;
inline constexpr uint32 chrome146_177_linux_desktopTcpStream = 0;
inline constexpr uint16 chrome146_177_linux_desktopRecordLength = 1794;
inline constexpr uint16 chrome146_177_linux_desktopHandshakeLength = 1790;
inline const vector<uint16> chrome146_177_linux_desktopCipherSuites = {0xEAEA, 0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome146_177_linux_desktopNonGreaseCipherSuites = {0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome146_177_linux_desktopSupportedGroups = {0x8A8A, 0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome146_177_linux_desktopNonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome146_177_linux_desktopExtensionOrder = {0x6A6A, 0x001B, 0x000A, 0xFE0D, 0x000B, 0x0023, 0x0010, 0x0017, 0xFF01, 0x0005, 0x0033, 0x002B, 0x000D, 0x0012, 0x002D, 0x0000, 0x44CD, 0x4A4A, 0x0029};
inline const vector<uint16> chrome146_177_linux_desktopNonGreaseExtensionsWithoutPadding = {0x001B, 0x000A, 0xFE0D, 0x000B, 0x0023, 0x0010, 0x0017, 0xFF01, 0x0005, 0x0033, 0x002B, 0x000D, 0x0012, 0x002D, 0x0000, 0x44CD, 0x0029};
inline const vector<string> chrome146_177_linux_desktopAlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> chrome146_177_linux_desktopCompressCertificateAlgorithms = {0x0002};
inline const vector<KeyShareExpectation> chrome146_177_linux_desktopKeyShareEntries = {{0x8A8A, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation chrome146_177_linux_desktopEch{true, 0x00, 0x0001, 0x0001, 32, 144};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/linux_desktop/chrome146_75_linux_desktop.clienthello.json
// fixture_id=chrome146_75_linux_desktop:frame5
inline constexpr const char chrome146_75_linux_desktopFixtureId[] = "chrome146_75_linux_desktop:frame5";
inline constexpr const char chrome146_75_linux_desktopSourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/Linux, desktop/chrome146.0.7680.75-1.pcapng";
inline constexpr const char chrome146_75_linux_desktopSourceSha256[] = "cfab11484e648613605053a3b4cffb0d36fb22379c8ef60f198fb6d2a2e5787b";
inline constexpr const char chrome146_75_linux_desktopCaptureDateUtc[] = "2026-04-07T02:56:06Z";
inline constexpr const char chrome146_75_linux_desktopParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char chrome146_75_linux_desktopScenarioId[] = "linux_desktop_chrome146_75_clienthello";
inline constexpr const char chrome146_75_linux_desktopRouteMode[] = "non_ru_egress";
inline constexpr const char chrome146_75_linux_desktopSni[] = "viiita.fun";
inline constexpr uint32 chrome146_75_linux_desktopFrameNumber = 5;
inline constexpr uint32 chrome146_75_linux_desktopTcpStream = 0;
inline constexpr uint16 chrome146_75_linux_desktopRecordLength = 1715;
inline constexpr uint16 chrome146_75_linux_desktopHandshakeLength = 1711;
inline const vector<uint16> chrome146_75_linux_desktopCipherSuites = {0xDADA, 0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome146_75_linux_desktopNonGreaseCipherSuites = {0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> chrome146_75_linux_desktopSupportedGroups = {0x7A7A, 0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome146_75_linux_desktopNonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> chrome146_75_linux_desktopExtensionOrder = {0xEAEA, 0xFF01, 0x0010, 0x0033, 0xFE0D, 0x0012, 0x000A, 0x0000, 0x0023, 0x0017, 0x001B, 0x000D, 0x002B, 0x000B, 0x0005, 0x002D, 0x44CD, 0x1A1A};
inline const vector<uint16> chrome146_75_linux_desktopNonGreaseExtensionsWithoutPadding = {0xFF01, 0x0010, 0x0033, 0xFE0D, 0x0012, 0x000A, 0x0000, 0x0023, 0x0017, 0x001B, 0x000D, 0x002B, 0x000B, 0x0005, 0x002D, 0x44CD};
inline const vector<string> chrome146_75_linux_desktopAlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> chrome146_75_linux_desktopCompressCertificateAlgorithms = {0x0002};
inline const vector<KeyShareExpectation> chrome146_75_linux_desktopKeyShareEntries = {{0x7A7A, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation chrome146_75_linux_desktopEch{true, 0x00, 0x0001, 0x0001, 32, 144};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/linux_desktop/firefox148_linux_desktop.clienthello.json
// fixture_id=firefox148_linux_desktop:frame5
inline constexpr const char firefox148_linux_desktopFixtureId[] = "firefox148_linux_desktop:frame5";
inline constexpr const char firefox148_linux_desktopSourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/Linux, desktop/clienthello-firefox148.0.2-ubuntu24.04.pcapng";
inline constexpr const char firefox148_linux_desktopSourceSha256[] = "c93bf5b06b764ad2f8162b79dfc5f96252c54f2b0de1d04f3fe37cb40b10c400";
inline constexpr const char firefox148_linux_desktopCaptureDateUtc[] = "2026-04-07T10:36:16Z";
inline constexpr const char firefox148_linux_desktopParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char firefox148_linux_desktopScenarioId[] = "linux_desktop_firefox148_clienthello";
inline constexpr const char firefox148_linux_desktopRouteMode[] = "non_ru_egress";
inline constexpr const char firefox148_linux_desktopSni[] = "viiita.fun";
inline constexpr uint32 firefox148_linux_desktopFrameNumber = 5;
inline constexpr uint32 firefox148_linux_desktopTcpStream = 0;
inline constexpr uint16 firefox148_linux_desktopRecordLength = 1890;
inline constexpr uint16 firefox148_linux_desktopHandshakeLength = 1886;
inline const vector<uint16> firefox148_linux_desktopCipherSuites = {0x1301, 0x1303, 0x1302, 0xC02B, 0xC02F, 0xCCA9, 0xCCA8, 0xC02C, 0xC030, 0xC00A, 0xC009, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> firefox148_linux_desktopNonGreaseCipherSuites = {0x1301, 0x1303, 0x1302, 0xC02B, 0xC02F, 0xCCA9, 0xCCA8, 0xC02C, 0xC030, 0xC00A, 0xC009, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> firefox148_linux_desktopSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019, 0x0100, 0x0101};
inline const vector<uint16> firefox148_linux_desktopNonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019, 0x0100, 0x0101};
inline const vector<uint16> firefox148_linux_desktopExtensionOrder = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0023, 0x0010, 0x0005, 0x0022, 0x0012, 0x0033, 0x002B, 0x000D, 0x002D, 0x001C, 0x001B, 0xFE0D};
inline const vector<uint16> firefox148_linux_desktopNonGreaseExtensionsWithoutPadding = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0023, 0x0010, 0x0005, 0x0022, 0x0012, 0x0033, 0x002B, 0x000D, 0x002D, 0x001C, 0x001B, 0xFE0D};
inline const vector<string> firefox148_linux_desktopAlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> firefox148_linux_desktopCompressCertificateAlgorithms = {0x0001, 0x0002, 0x0003};
inline const vector<KeyShareExpectation> firefox148_linux_desktopKeyShareEntries = {{0x11EC, 1216, false}, {0x001D, 32, false}, {0x0017, 65, false}};
inline constexpr EchExpectation firefox148_linux_desktopEch{true, 0x00, 0x0001, 0x0003, 32, 239};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/linux_desktop/firefox149_linux_desktop.clienthello.json
// fixture_id=firefox149_linux_desktop:frame5
inline constexpr const char firefox149_linux_desktopFixtureId[] = "firefox149_linux_desktop:frame5";
inline constexpr const char firefox149_linux_desktopSourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/Linux, desktop/firefox149.0.pcapng";
inline constexpr const char firefox149_linux_desktopSourceSha256[] = "f7e0c07cc15b25654cab26a29cafcc16fbdcec4304cacbe0ffc831fca93a2fea";
inline constexpr const char firefox149_linux_desktopCaptureDateUtc[] = "2026-04-07T03:50:15Z";
inline constexpr const char firefox149_linux_desktopParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char firefox149_linux_desktopScenarioId[] = "linux_desktop_firefox149_clienthello";
inline constexpr const char firefox149_linux_desktopRouteMode[] = "non_ru_egress";
inline constexpr const char firefox149_linux_desktopSni[] = "viiita.fun";
inline constexpr uint32 firefox149_linux_desktopFrameNumber = 5;
inline constexpr uint32 firefox149_linux_desktopTcpStream = 0;
inline constexpr uint16 firefox149_linux_desktopRecordLength = 1890;
inline constexpr uint16 firefox149_linux_desktopHandshakeLength = 1886;
inline const vector<uint16> firefox149_linux_desktopCipherSuites = {0x1301, 0x1303, 0x1302, 0xC02B, 0xC02F, 0xCCA9, 0xCCA8, 0xC02C, 0xC030, 0xC00A, 0xC009, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> firefox149_linux_desktopNonGreaseCipherSuites = {0x1301, 0x1303, 0x1302, 0xC02B, 0xC02F, 0xCCA9, 0xCCA8, 0xC02C, 0xC030, 0xC00A, 0xC009, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> firefox149_linux_desktopSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019, 0x0100, 0x0101};
inline const vector<uint16> firefox149_linux_desktopNonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019, 0x0100, 0x0101};
inline const vector<uint16> firefox149_linux_desktopExtensionOrder = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0023, 0x0010, 0x0005, 0x0022, 0x0012, 0x0033, 0x002B, 0x000D, 0x002D, 0x001C, 0x001B, 0xFE0D};
inline const vector<uint16> firefox149_linux_desktopNonGreaseExtensionsWithoutPadding = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0023, 0x0010, 0x0005, 0x0022, 0x0012, 0x0033, 0x002B, 0x000D, 0x002D, 0x001C, 0x001B, 0xFE0D};
inline const vector<string> firefox149_linux_desktopAlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> firefox149_linux_desktopCompressCertificateAlgorithms = {0x0001, 0x0002, 0x0003};
inline const vector<KeyShareExpectation> firefox149_linux_desktopKeyShareEntries = {{0x11EC, 1216, false}, {0x001D, 32, false}, {0x0017, 65, false}};
inline constexpr EchExpectation firefox149_linux_desktopEch{true, 0x00, 0x0001, 0x0001, 32, 239};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/linux_desktop/tdesktop673_linux_desktop.clienthello.json
// fixture_id=tdesktop673_linux_desktop:frame5
inline constexpr const char tdesktop673_linux_desktopFixtureId[] = "tdesktop673_linux_desktop:frame5";
inline constexpr const char tdesktop673_linux_desktopSourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/Linux, desktop/clienthello-tdesktop6.7.3-ubuntu24.04.pcapng";
inline constexpr const char tdesktop673_linux_desktopSourceSha256[] = "7713ff5b35fe02cbcc16350019da0fd21d68011c7fe1ccece801ae7323f72487";
inline constexpr const char tdesktop673_linux_desktopCaptureDateUtc[] = "2026-04-07T10:02:20Z";
inline constexpr const char tdesktop673_linux_desktopParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char tdesktop673_linux_desktopScenarioId[] = "linux_desktop_tdesktop673_clienthello";
inline constexpr const char tdesktop673_linux_desktopRouteMode[] = "non_ru_egress";
inline constexpr const char tdesktop673_linux_desktopSni[] = "viiita.fun";
inline constexpr uint32 tdesktop673_linux_desktopFrameNumber = 5;
inline constexpr uint32 tdesktop673_linux_desktopTcpStream = 0;
inline constexpr uint16 tdesktop673_linux_desktopRecordLength = 1779;
inline constexpr uint16 tdesktop673_linux_desktopHandshakeLength = 1775;
inline const vector<uint16> tdesktop673_linux_desktopCipherSuites = {0xDADA, 0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> tdesktop673_linux_desktopNonGreaseCipherSuites = {0x1301, 0x1302, 0x1303, 0xC02B, 0xC02F, 0xC02C, 0xC030, 0xCCA9, 0xCCA8, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> tdesktop673_linux_desktopSupportedGroups = {0x1A1A, 0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> tdesktop673_linux_desktopNonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018};
inline const vector<uint16> tdesktop673_linux_desktopExtensionOrder = {0x6A6A, 0x002D, 0xFE0D, 0x002B, 0x0012, 0x44CD, 0x000A, 0x0023, 0x000B, 0x0005, 0x0000, 0x0010, 0x0033, 0x0017, 0xFF01, 0x000D, 0x001B, 0x4A4A};
inline const vector<uint16> tdesktop673_linux_desktopNonGreaseExtensionsWithoutPadding = {0x002D, 0xFE0D, 0x002B, 0x0012, 0x44CD, 0x000A, 0x0023, 0x000B, 0x0005, 0x0000, 0x0010, 0x0033, 0x0017, 0xFF01, 0x000D, 0x001B};
inline const vector<string> tdesktop673_linux_desktopAlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> tdesktop673_linux_desktopCompressCertificateAlgorithms = {0x0002};
inline const vector<KeyShareExpectation> tdesktop673_linux_desktopKeyShareEntries = {{0x1A1A, 1, true}, {0x11EC, 1216, false}, {0x001D, 32, false}};
inline constexpr EchExpectation tdesktop673_linux_desktopEch{true, 0x00, 0x0001, 0x0001, 32, 208};

// merged_from=/home/david_osipov/tdlib-obf/test/analysis/fixtures/clienthello/macos/firefox149_macos26_3.clienthello.json
// fixture_id=firefox149_macos26_3:frame8
inline constexpr const char firefox149_macos26_3FixtureId[] = "firefox149_macos26_3:frame8";
inline constexpr const char firefox149_macos26_3SourcePath[] = "/home/david_osipov/tdlib-obf/docs/Samples/Traffic dumps/macOS/MacOS Tahoe 26.3, macbook m4 pro, firefox 149.0.pcap";
inline constexpr const char firefox149_macos26_3SourceSha256[] = "ce980035f103fc0dcae949cc3feaeeb478da9fc9709b4cd9688d0a235c694cb1";
inline constexpr const char firefox149_macos26_3CaptureDateUtc[] = "2026-04-07T13:15:43Z";
inline constexpr const char firefox149_macos26_3ParserVersion[] = "tls-clienthello-parser-v1";
inline constexpr const char firefox149_macos26_3ScenarioId[] = "macos26_3_firefox149_clienthello";
inline constexpr const char firefox149_macos26_3RouteMode[] = "non_ru_egress";
inline constexpr const char firefox149_macos26_3Sni[] = "kf58p1vqbctehrki.mooo.com";
inline constexpr uint32 firefox149_macos26_3FrameNumber = 8;
inline constexpr uint32 firefox149_macos26_3TcpStream = 1;
inline constexpr uint16 firefox149_macos26_3RecordLength = 2213;
inline constexpr uint16 firefox149_macos26_3HandshakeLength = 2209;
inline const vector<uint16> firefox149_macos26_3CipherSuites = {0x1301, 0x1303, 0x1302, 0xC02B, 0xC02F, 0xCCA9, 0xCCA8, 0xC02C, 0xC030, 0xC00A, 0xC009, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> firefox149_macos26_3NonGreaseCipherSuites = {0x1301, 0x1303, 0x1302, 0xC02B, 0xC02F, 0xCCA9, 0xCCA8, 0xC02C, 0xC030, 0xC00A, 0xC009, 0xC013, 0xC014, 0x009C, 0x009D, 0x002F, 0x0035};
inline const vector<uint16> firefox149_macos26_3SupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019, 0x0100, 0x0101};
inline const vector<uint16> firefox149_macos26_3NonGreaseSupportedGroups = {0x11EC, 0x001D, 0x0017, 0x0018, 0x0019, 0x0100, 0x0101};
inline const vector<uint16> firefox149_macos26_3ExtensionOrder = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x0022, 0x0012, 0x0033, 0x002B, 0x000D, 0x002D, 0x001C, 0x001B, 0xFE0D, 0x0029};
inline const vector<uint16> firefox149_macos26_3NonGreaseExtensionsWithoutPadding = {0x0000, 0x0017, 0xFF01, 0x000A, 0x000B, 0x0010, 0x0005, 0x0022, 0x0012, 0x0033, 0x002B, 0x000D, 0x002D, 0x001C, 0x001B, 0xFE0D, 0x0029};
inline const vector<string> firefox149_macos26_3AlpnProtocols = {"h2", "http/1.1"};
inline const vector<uint16> firefox149_macos26_3CompressCertificateAlgorithms = {0x0001, 0x0002, 0x0003};
inline const vector<KeyShareExpectation> firefox149_macos26_3KeyShareEntries = {{0x11EC, 1216, false}, {0x001D, 32, false}, {0x0017, 65, false}};
inline constexpr EchExpectation firefox149_macos26_3Ech{true, 0x00, 0x0001, 0x0001, 32, 399};

// reviewed aliases used by PR-2 tests
inline const auto &kChromeLinuxDesktopReferenceNonGreaseCipherSuites = chrome144_linux_desktopNonGreaseCipherSuites;
inline const auto &kChromeLinuxDesktopReferenceCipherSuites = chrome144_linux_desktopCipherSuites;
inline const auto &kChromeLinuxDesktopReferenceSupportedGroups = chrome144_linux_desktopSupportedGroups;
inline const auto &kChromeLinuxDesktopReferenceNonGreaseSupportedGroups = chrome144_linux_desktopNonGreaseSupportedGroups;
inline const auto &kChromeLinuxDesktopReferenceExtensionOrder = chrome144_linux_desktopExtensionOrder;
inline const auto &kChromeLinuxDesktopReferenceNonGreaseExtensionsWithoutPadding = chrome144_linux_desktopNonGreaseExtensionsWithoutPadding;
inline const auto &kChromeLinuxDesktopReferenceCompressCertificateAlgorithms = chrome144_linux_desktopCompressCertificateAlgorithms;
inline const auto &kChromeLinuxDesktopReferenceKeyShareEntries = chrome144_linux_desktopKeyShareEntries;
inline constexpr auto kChromeLinuxDesktopReferenceEch = chrome144_linux_desktopEch;
inline const auto &kFirefoxLinuxDesktopReferenceNonGreaseCipherSuites = firefox148_linux_desktopNonGreaseCipherSuites;
inline const auto &kFirefoxLinuxDesktopReferenceCipherSuites = firefox148_linux_desktopCipherSuites;
inline const auto &kFirefoxLinuxDesktopReferenceSupportedGroups = firefox148_linux_desktopSupportedGroups;
inline const auto &kFirefoxLinuxDesktopReferenceNonGreaseSupportedGroups = firefox148_linux_desktopNonGreaseSupportedGroups;
inline const auto &kFirefoxLinuxDesktopReferenceExtensionOrder = firefox148_linux_desktopExtensionOrder;
inline const auto &kFirefoxLinuxDesktopReferenceNonGreaseExtensionsWithoutPadding = firefox148_linux_desktopNonGreaseExtensionsWithoutPadding;
inline const auto &kFirefoxLinuxDesktopReferenceCompressCertificateAlgorithms = firefox148_linux_desktopCompressCertificateAlgorithms;
inline const auto &kFirefoxLinuxDesktopReferenceKeyShareEntries = firefox148_linux_desktopKeyShareEntries;
inline constexpr auto kFirefoxLinuxDesktopReferenceEch = firefox148_linux_desktopEch;
inline const auto &kChrome146_75LinuxDesktopReferenceNonGreaseCipherSuites = chrome146_75_linux_desktopNonGreaseCipherSuites;
inline const auto &kChrome146_75LinuxDesktopReferenceCipherSuites = chrome146_75_linux_desktopCipherSuites;
inline const auto &kChrome146_75LinuxDesktopReferenceSupportedGroups = chrome146_75_linux_desktopSupportedGroups;
inline const auto &kChrome146_75LinuxDesktopReferenceNonGreaseSupportedGroups = chrome146_75_linux_desktopNonGreaseSupportedGroups;
inline const auto &kChrome146_75LinuxDesktopReferenceExtensionOrder = chrome146_75_linux_desktopExtensionOrder;
inline const auto &kChrome146_75LinuxDesktopReferenceNonGreaseExtensionsWithoutPadding = chrome146_75_linux_desktopNonGreaseExtensionsWithoutPadding;
inline const auto &kChrome146_75LinuxDesktopReferenceCompressCertificateAlgorithms = chrome146_75_linux_desktopCompressCertificateAlgorithms;
inline const auto &kChrome146_75LinuxDesktopReferenceKeyShareEntries = chrome146_75_linux_desktopKeyShareEntries;
inline constexpr auto kChrome146_75LinuxDesktopReferenceEch = chrome146_75_linux_desktopEch;
inline const auto &kChrome146_177LinuxDesktopReferenceNonGreaseCipherSuites = chrome146_177_linux_desktopNonGreaseCipherSuites;
inline const auto &kChrome146_177LinuxDesktopReferenceCipherSuites = chrome146_177_linux_desktopCipherSuites;
inline const auto &kChrome146_177LinuxDesktopReferenceSupportedGroups = chrome146_177_linux_desktopSupportedGroups;
inline const auto &kChrome146_177LinuxDesktopReferenceNonGreaseSupportedGroups = chrome146_177_linux_desktopNonGreaseSupportedGroups;
inline const auto &kChrome146_177LinuxDesktopReferenceExtensionOrder = chrome146_177_linux_desktopExtensionOrder;
inline const auto &kChrome146_177LinuxDesktopReferenceNonGreaseExtensionsWithoutPadding = chrome146_177_linux_desktopNonGreaseExtensionsWithoutPadding;
inline const auto &kChrome146_177LinuxDesktopReferenceCompressCertificateAlgorithms = chrome146_177_linux_desktopCompressCertificateAlgorithms;
inline const auto &kChrome146_177LinuxDesktopReferenceKeyShareEntries = chrome146_177_linux_desktopKeyShareEntries;
inline constexpr auto kChrome146_177LinuxDesktopReferenceEch = chrome146_177_linux_desktopEch;
inline const auto &kTdesktop673LinuxDesktopReferenceNonGreaseCipherSuites = tdesktop673_linux_desktopNonGreaseCipherSuites;
inline const auto &kTdesktop673LinuxDesktopReferenceCipherSuites = tdesktop673_linux_desktopCipherSuites;
inline const auto &kTdesktop673LinuxDesktopReferenceSupportedGroups = tdesktop673_linux_desktopSupportedGroups;
inline const auto &kTdesktop673LinuxDesktopReferenceNonGreaseSupportedGroups = tdesktop673_linux_desktopNonGreaseSupportedGroups;
inline const auto &kTdesktop673LinuxDesktopReferenceExtensionOrder = tdesktop673_linux_desktopExtensionOrder;
inline const auto &kTdesktop673LinuxDesktopReferenceNonGreaseExtensionsWithoutPadding = tdesktop673_linux_desktopNonGreaseExtensionsWithoutPadding;
inline const auto &kTdesktop673LinuxDesktopReferenceCompressCertificateAlgorithms = tdesktop673_linux_desktopCompressCertificateAlgorithms;
inline const auto &kTdesktop673LinuxDesktopReferenceKeyShareEntries = tdesktop673_linux_desktopKeyShareEntries;
inline constexpr auto kTdesktop673LinuxDesktopReferenceEch = tdesktop673_linux_desktopEch;
inline const auto &kFirefox149LinuxDesktopReferenceNonGreaseCipherSuites = firefox149_linux_desktopNonGreaseCipherSuites;
inline const auto &kFirefox149LinuxDesktopReferenceCipherSuites = firefox149_linux_desktopCipherSuites;
inline const auto &kFirefox149LinuxDesktopReferenceSupportedGroups = firefox149_linux_desktopSupportedGroups;
inline const auto &kFirefox149LinuxDesktopReferenceNonGreaseSupportedGroups = firefox149_linux_desktopNonGreaseSupportedGroups;
inline const auto &kFirefox149LinuxDesktopReferenceExtensionOrder = firefox149_linux_desktopExtensionOrder;
inline const auto &kFirefox149LinuxDesktopReferenceNonGreaseExtensionsWithoutPadding = firefox149_linux_desktopNonGreaseExtensionsWithoutPadding;
inline const auto &kFirefox149LinuxDesktopReferenceCompressCertificateAlgorithms = firefox149_linux_desktopCompressCertificateAlgorithms;
inline const auto &kFirefox149LinuxDesktopReferenceKeyShareEntries = firefox149_linux_desktopKeyShareEntries;
inline constexpr auto kFirefox149LinuxDesktopReferenceEch = firefox149_linux_desktopEch;
}  // namespace reviewed
}  // namespace fixtures
}  // namespace test
}  // namespace mtproto
}  // namespace td
