name: SonarCloud TDLib

on:
  push:
    branches: [master]
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            make git zlib1g-dev libssl-dev gperf php-cli cmake \
            clang-18 libc++-18-dev libc++abi-18-dev ninja-build lld

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v6

      - name: Configure and build TDLib
        run: |
          env CXXFLAGS="-stdlib=libc++" \
              CC=/usr/bin/clang-18 \
              CXX=/usr/bin/clang++-18 \
              cmake -S . -B build \
                    -G Ninja \
                    -DBUILD_SHARED_LIBS=ON \
                    -DCMAKE_BUILD_TYPE=Release \
                    -DCMAKE_INSTALL_PREFIX:PATH=./tdlib \
                    -DTD_ENABLE_LLD=ON

          build-wrapper-linux-x86-64 --out-dir build/bw-output \
            cmake --build build --target install --parallel $(nproc)

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.cfamily.compile-commands=build/bw-output/compile_commands.json
